
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model SeasonalPeriod
 * 
 */
export type SeasonalPeriod = Prisma.SeasonalPeriodModel
/**
 * Model WeekdaySchedule
 * 
 */
export type WeekdaySchedule = Prisma.WeekdayScheduleModel
/**
 * Model DaySchedule
 * 
 */
export type DaySchedule = Prisma.DayScheduleModel
/**
 * Model Nutrition
 * 
 */
export type Nutrition = Prisma.NutritionModel
/**
 * Model ItemFee
 * 
 */
export type ItemFee = Prisma.ItemFeeModel
/**
 * Model Choice
 * 
 */
export type Choice = Prisma.ChoiceModel
/**
 * Model AppliedOption
 * 
 */
export type AppliedOption = Prisma.AppliedOptionModel
/**
 * Model ChoiceAdjustment
 * 
 */
export type ChoiceAdjustment = Prisma.ChoiceAdjustmentModel
/**
 * Model PriceAdjustment
 * 
 */
export type PriceAdjustment = Prisma.PriceAdjustmentModel
/**
 * Model OrderItem
 * 
 */
export type OrderItem = Prisma.OrderItemModel
/**
 * Model SelectedOption
 * 
 */
export type SelectedOption = Prisma.SelectedOptionModel
/**
 * Model TaxSetting
 * 
 */
export type TaxSetting = Prisma.TaxSettingModel
/**
 * Model GlobalFee
 * 
 */
export type GlobalFee = Prisma.GlobalFeeModel
/**
 * Model DeliveryPricingTier
 * 
 */
export type DeliveryPricingTier = Prisma.DeliveryPricingTierModel
/**
 * Model WeeklySchedule
 * 
 */
export type WeeklySchedule = Prisma.WeeklyScheduleModel
/**
 * Model ScheduleTimeSlot
 * 
 */
export type ScheduleTimeSlot = Prisma.ScheduleTimeSlotModel
/**
 * Model DayHours
 * 
 */
export type DayHours = Prisma.DayHoursModel
/**
 * Model SpecialClosure
 * 
 */
export type SpecialClosure = Prisma.SpecialClosureModel
/**
 * Model KitchenStage
 * 
 */
export type KitchenStage = Prisma.KitchenStageModel
/**
 * Model MenuCategory
 * 
 */
export type MenuCategory = Prisma.MenuCategoryModel
/**
 * Model MenuItem
 * 
 */
export type MenuItem = Prisma.MenuItemModel
/**
 * Model OptionCategory
 * 
 */
export type OptionCategory = Prisma.OptionCategoryModel
/**
 * Model Option
 * 
 */
export type Option = Prisma.OptionModel
/**
 * Model MenuRules
 * 
 */
export type MenuRules = Prisma.MenuRulesModel
/**
 * Model Order
 * 
 */
export type Order = Prisma.OrderModel
/**
 * Model Customer
 * 
 */
export type Customer = Prisma.CustomerModel
/**
 * Model Restaurant
 * 
 */
export type Restaurant = Prisma.RestaurantModel
/**
 * Model FinancialSettings
 * 
 */
export type FinancialSettings = Prisma.FinancialSettingsModel
/**
 * Model DeliverySettings
 * 
 */
export type DeliverySettings = Prisma.DeliverySettingsModel
/**
 * Model StoreHours
 * 
 */
export type StoreHours = Prisma.StoreHoursModel
/**
 * Model RolePermissions
 * 
 */
export type RolePermissions = Prisma.RolePermissionsModel
/**
 * Model Transaction
 * 
 */
export type Transaction = Prisma.TransactionModel
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model UserRestaurant
 * 
 */
export type UserRestaurant = Prisma.UserRestaurantModel
