
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ChoiceAdjustment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ChoiceAdjustment
 * 
 */
export type ChoiceAdjustmentModel = runtime.Types.Result.DefaultSelection<Prisma.$ChoiceAdjustmentPayload>






export type ChoiceAdjustmentCompositeListFilter = {
  equals?: Prisma.ChoiceAdjustmentObjectEqualityInput[]
  every?: Prisma.ChoiceAdjustmentWhereInput
  some?: Prisma.ChoiceAdjustmentWhereInput
  none?: Prisma.ChoiceAdjustmentWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type PriceAdjustmentObjectEqualityInput = {
  targetOptionId: string
  targetChoiceId?: string | null
  adjustmentType: string
  value: number
}

export type PriceAdjustmentCreateInput = {
  targetOptionId: string
  targetChoiceId?: string | null
  adjustmentType: string
  value: number
}

export type ChoiceAdjustmentWhereInput = {
  AND?: Prisma.ChoiceAdjustmentWhereInput | Prisma.ChoiceAdjustmentWhereInput[]
  OR?: Prisma.ChoiceAdjustmentWhereInput[]
  NOT?: Prisma.ChoiceAdjustmentWhereInput | Prisma.ChoiceAdjustmentWhereInput[]
  choiceId?: Prisma.StringFilter<"ChoiceAdjustment"> | string
  priceAdjustment?: Prisma.FloatFilter<"ChoiceAdjustment"> | number
  isAvailable?: Prisma.BoolFilter<"ChoiceAdjustment"> | boolean
  isDefault?: Prisma.BoolFilter<"ChoiceAdjustment"> | boolean
  adjustments?: Prisma.PriceAdjustmentCompositeListFilter | Prisma.PriceAdjustmentObjectEqualityInput[]
}

export type ChoiceAdjustmentListUpdateEnvelopeInput = {
  set?: Prisma.ChoiceAdjustmentCreateInput | Prisma.ChoiceAdjustmentCreateInput[]
  push?: Prisma.ChoiceAdjustmentCreateInput | Prisma.ChoiceAdjustmentCreateInput[]
  updateMany?: Prisma.ChoiceAdjustmentUpdateManyInput
  deleteMany?: Prisma.ChoiceAdjustmentDeleteManyInput
}

export type ChoiceAdjustmentUpdateManyInput = {
  where: Prisma.ChoiceAdjustmentWhereInput
  data: Prisma.ChoiceAdjustmentUpdateInput
}

export type ChoiceAdjustmentDeleteManyInput = {
  where: Prisma.ChoiceAdjustmentWhereInput
}

export type ChoiceAdjustmentUpdateInput = {
  choiceId?: Prisma.StringFieldUpdateOperationsInput | string
  priceAdjustment?: Prisma.FloatFieldUpdateOperationsInput | number
  isAvailable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  adjustments?: Prisma.XOR<Prisma.PriceAdjustmentListUpdateEnvelopeInput, Prisma.PriceAdjustmentCreateInput> | Prisma.PriceAdjustmentCreateInput[]
}



export type ChoiceAdjustmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  choiceId?: boolean
  priceAdjustment?: boolean
  isAvailable?: boolean
  isDefault?: boolean
  adjustments?: boolean | Prisma.PriceAdjustmentDefaultArgs<ExtArgs>
}, ExtArgs["result"]["choiceAdjustment"]>



export type ChoiceAdjustmentSelectScalar = {
  choiceId?: boolean
  priceAdjustment?: boolean
  isAvailable?: boolean
  isDefault?: boolean
}

export type ChoiceAdjustmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"choiceId" | "priceAdjustment" | "isAvailable" | "isDefault" | "adjustments", ExtArgs["result"]["choiceAdjustment"]>
export type ChoiceAdjustmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $ChoiceAdjustmentPayload = {
  name: "ChoiceAdjustment"
  objects: {}
  scalars: {
    choiceId: string
    priceAdjustment: number
    isAvailable: boolean
    isDefault: boolean
  }
  composites: {
    adjustments: Prisma.$PriceAdjustmentPayload[]
  }
}

export type ChoiceAdjustmentGetPayload<S extends boolean | null | undefined | ChoiceAdjustmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChoiceAdjustmentPayload, S>





/**
 * Fields of the ChoiceAdjustment model
 */
export interface ChoiceAdjustmentFieldRefs {
  readonly choiceId: Prisma.FieldRef<"ChoiceAdjustment", 'String'>
  readonly priceAdjustment: Prisma.FieldRef<"ChoiceAdjustment", 'Float'>
  readonly isAvailable: Prisma.FieldRef<"ChoiceAdjustment", 'Boolean'>
  readonly isDefault: Prisma.FieldRef<"ChoiceAdjustment", 'Boolean'>
}
    

// Custom InputTypes
/**
 * ChoiceAdjustment without action
 */
export type ChoiceAdjustmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ChoiceAdjustment
   */
  select?: Prisma.ChoiceAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ChoiceAdjustment
   */
  omit?: Prisma.ChoiceAdjustmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ChoiceAdjustmentInclude<ExtArgs> | null
}
