
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Choice` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Choice
 * 
 */
export type ChoiceModel = runtime.Types.Result.DefaultSelection<Prisma.$ChoicePayload>






export type ChoiceCompositeListFilter = {
  equals?: Prisma.ChoiceObjectEqualityInput[]
  every?: Prisma.ChoiceWhereInput
  some?: Prisma.ChoiceWhereInput
  none?: Prisma.ChoiceWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type ChoiceOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ChoiceListCreateEnvelopeInput = {
  set?: Prisma.ChoiceCreateInput | Prisma.ChoiceCreateInput[]
}

export type ChoiceListUpdateEnvelopeInput = {
  set?: Prisma.ChoiceCreateInput | Prisma.ChoiceCreateInput[]
  push?: Prisma.ChoiceCreateInput | Prisma.ChoiceCreateInput[]
  updateMany?: Prisma.ChoiceUpdateManyInput
  deleteMany?: Prisma.ChoiceDeleteManyInput
}

export type ChoiceWhereInput = {
  AND?: Prisma.ChoiceWhereInput | Prisma.ChoiceWhereInput[]
  OR?: Prisma.ChoiceWhereInput[]
  NOT?: Prisma.ChoiceWhereInput | Prisma.ChoiceWhereInput[]
  id?: Prisma.StringFilter<"Choice"> | string
  name?: Prisma.StringFilter<"Choice"> | string
  basePrice?: Prisma.FloatFilter<"Choice"> | number
  isDefault?: Prisma.BoolFilter<"Choice"> | boolean
  disableWhenFinishInventory?: Prisma.BoolFilter<"Choice"> | boolean
  isAvailable?: Prisma.BoolFilter<"Choice"> | boolean
  inventoryCount?: Prisma.IntFilter<"Choice"> | number
}

export type ChoiceUpdateManyInput = {
  where: Prisma.ChoiceWhereInput
  data: Prisma.ChoiceUpdateInput
}

export type ChoiceDeleteManyInput = {
  where: Prisma.ChoiceWhereInput
}

export type ChoiceUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  basePrice?: Prisma.FloatFieldUpdateOperationsInput | number
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
  disableWhenFinishInventory?: Prisma.BoolFieldUpdateOperationsInput | boolean
  isAvailable?: Prisma.BoolFieldUpdateOperationsInput | boolean
  inventoryCount?: Prisma.IntFieldUpdateOperationsInput | number
}



export type ChoiceSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  basePrice?: boolean
  isDefault?: boolean
  disableWhenFinishInventory?: boolean
  isAvailable?: boolean
  inventoryCount?: boolean
}, ExtArgs["result"]["choice"]>



export type ChoiceSelectScalar = {
  id?: boolean
  name?: boolean
  basePrice?: boolean
  isDefault?: boolean
  disableWhenFinishInventory?: boolean
  isAvailable?: boolean
  inventoryCount?: boolean
}

export type ChoiceOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "basePrice" | "isDefault" | "disableWhenFinishInventory" | "isAvailable" | "inventoryCount", ExtArgs["result"]["choice"]>

export type $ChoicePayload = {
  name: "Choice"
  objects: {}
  scalars: {
    id: string
    name: string
    basePrice: number
    isDefault: boolean
    disableWhenFinishInventory: boolean
    isAvailable: boolean
    inventoryCount: number
  }
  composites: {}
}

export type ChoiceGetPayload<S extends boolean | null | undefined | ChoiceDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ChoicePayload, S>





/**
 * Fields of the Choice model
 */
export interface ChoiceFieldRefs {
  readonly id: Prisma.FieldRef<"Choice", 'String'>
  readonly name: Prisma.FieldRef<"Choice", 'String'>
  readonly basePrice: Prisma.FieldRef<"Choice", 'Float'>
  readonly isDefault: Prisma.FieldRef<"Choice", 'Boolean'>
  readonly disableWhenFinishInventory: Prisma.FieldRef<"Choice", 'Boolean'>
  readonly isAvailable: Prisma.FieldRef<"Choice", 'Boolean'>
  readonly inventoryCount: Prisma.FieldRef<"Choice", 'Int'>
}
    

// Custom InputTypes
/**
 * Choice without action
 */
export type ChoiceDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Choice
   */
  select?: Prisma.ChoiceSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Choice
   */
  omit?: Prisma.ChoiceOmit<ExtArgs> | null
}
