
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `DaySchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DaySchedule
 * 
 */
export type DayScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$DaySchedulePayload>






export type DayScheduleOrderByInput = {
  available?: Prisma.SortOrder
  start?: Prisma.SortOrder
  end?: Prisma.SortOrder
}

export type DayScheduleCompositeFilter = {
  equals?: Prisma.DayScheduleObjectEqualityInput
  is?: Prisma.DayScheduleWhereInput
  isNot?: Prisma.DayScheduleWhereInput
}

export type DayScheduleWhereInput = {
  AND?: Prisma.DayScheduleWhereInput | Prisma.DayScheduleWhereInput[]
  OR?: Prisma.DayScheduleWhereInput[]
  NOT?: Prisma.DayScheduleWhereInput | Prisma.DayScheduleWhereInput[]
  available?: Prisma.BoolFilter<"DaySchedule"> | boolean
  start?: Prisma.StringFilter<"DaySchedule"> | string
  end?: Prisma.StringFilter<"DaySchedule"> | string
}

export type DayScheduleUpdateEnvelopeInput = {
  set?: Prisma.DayScheduleCreateInput
  update?: Prisma.DayScheduleUpdateInput
}

export type DayScheduleUpdateInput = {
  available?: Prisma.BoolFieldUpdateOperationsInput | boolean
  start?: Prisma.StringFieldUpdateOperationsInput | string
  end?: Prisma.StringFieldUpdateOperationsInput | string
}



export type DayScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  available?: boolean
  start?: boolean
  end?: boolean
}, ExtArgs["result"]["daySchedule"]>



export type DayScheduleSelectScalar = {
  available?: boolean
  start?: boolean
  end?: boolean
}

export type DayScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"available" | "start" | "end", ExtArgs["result"]["daySchedule"]>

export type $DaySchedulePayload = {
  name: "DaySchedule"
  objects: {}
  scalars: {
    available: boolean
    start: string
    end: string
  }
  composites: {}
}

export type DayScheduleGetPayload<S extends boolean | null | undefined | DayScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DaySchedulePayload, S>





/**
 * Fields of the DaySchedule model
 */
export interface DayScheduleFieldRefs {
  readonly available: Prisma.FieldRef<"DaySchedule", 'Boolean'>
  readonly start: Prisma.FieldRef<"DaySchedule", 'String'>
  readonly end: Prisma.FieldRef<"DaySchedule", 'String'>
}
    

// Custom InputTypes
/**
 * DaySchedule without action
 */
export type DayScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DaySchedule
   */
  select?: Prisma.DayScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DaySchedule
   */
  omit?: Prisma.DayScheduleOmit<ExtArgs> | null
}
