
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `DeliveryPricingTier` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model DeliveryPricingTier
 * 
 */
export type DeliveryPricingTierModel = runtime.Types.Result.DefaultSelection<Prisma.$DeliveryPricingTierPayload>






export type DeliveryPricingTierCompositeListFilter = {
  equals?: Prisma.DeliveryPricingTierObjectEqualityInput[]
  every?: Prisma.DeliveryPricingTierWhereInput
  some?: Prisma.DeliveryPricingTierWhereInput
  none?: Prisma.DeliveryPricingTierWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type DeliveryPricingTierOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type DeliveryPricingTierListCreateEnvelopeInput = {
  set?: Prisma.DeliveryPricingTierCreateInput | Prisma.DeliveryPricingTierCreateInput[]
}

export type DeliveryPricingTierListUpdateEnvelopeInput = {
  set?: Prisma.DeliveryPricingTierCreateInput | Prisma.DeliveryPricingTierCreateInput[]
  push?: Prisma.DeliveryPricingTierCreateInput | Prisma.DeliveryPricingTierCreateInput[]
  updateMany?: Prisma.DeliveryPricingTierUpdateManyInput
  deleteMany?: Prisma.DeliveryPricingTierDeleteManyInput
}

export type DeliveryPricingTierWhereInput = {
  AND?: Prisma.DeliveryPricingTierWhereInput | Prisma.DeliveryPricingTierWhereInput[]
  OR?: Prisma.DeliveryPricingTierWhereInput[]
  NOT?: Prisma.DeliveryPricingTierWhereInput | Prisma.DeliveryPricingTierWhereInput[]
  name?: Prisma.StringFilter<"DeliveryPricingTier"> | string
  distanceCovered?: Prisma.FloatFilter<"DeliveryPricingTier"> | number
  baseFee?: Prisma.FloatFilter<"DeliveryPricingTier"> | number
  additionalFeePerUnit?: Prisma.FloatFilter<"DeliveryPricingTier"> | number
  isDefault?: Prisma.BoolFilter<"DeliveryPricingTier"> | boolean
}

export type DeliveryPricingTierUpdateManyInput = {
  where: Prisma.DeliveryPricingTierWhereInput
  data: Prisma.DeliveryPricingTierUpdateInput
}

export type DeliveryPricingTierDeleteManyInput = {
  where: Prisma.DeliveryPricingTierWhereInput
}

export type DeliveryPricingTierUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  distanceCovered?: Prisma.FloatFieldUpdateOperationsInput | number
  baseFee?: Prisma.FloatFieldUpdateOperationsInput | number
  additionalFeePerUnit?: Prisma.FloatFieldUpdateOperationsInput | number
  isDefault?: Prisma.BoolFieldUpdateOperationsInput | boolean
}



export type DeliveryPricingTierSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  distanceCovered?: boolean
  baseFee?: boolean
  additionalFeePerUnit?: boolean
  isDefault?: boolean
}, ExtArgs["result"]["deliveryPricingTier"]>



export type DeliveryPricingTierSelectScalar = {
  name?: boolean
  distanceCovered?: boolean
  baseFee?: boolean
  additionalFeePerUnit?: boolean
  isDefault?: boolean
}

export type DeliveryPricingTierOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "distanceCovered" | "baseFee" | "additionalFeePerUnit" | "isDefault", ExtArgs["result"]["deliveryPricingTier"]>

export type $DeliveryPricingTierPayload = {
  name: "DeliveryPricingTier"
  objects: {}
  scalars: {
    name: string
    distanceCovered: number
    baseFee: number
    additionalFeePerUnit: number
    isDefault: boolean
  }
  composites: {}
}

export type DeliveryPricingTierGetPayload<S extends boolean | null | undefined | DeliveryPricingTierDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$DeliveryPricingTierPayload, S>





/**
 * Fields of the DeliveryPricingTier model
 */
export interface DeliveryPricingTierFieldRefs {
  readonly name: Prisma.FieldRef<"DeliveryPricingTier", 'String'>
  readonly distanceCovered: Prisma.FieldRef<"DeliveryPricingTier", 'Float'>
  readonly baseFee: Prisma.FieldRef<"DeliveryPricingTier", 'Float'>
  readonly additionalFeePerUnit: Prisma.FieldRef<"DeliveryPricingTier", 'Float'>
  readonly isDefault: Prisma.FieldRef<"DeliveryPricingTier", 'Boolean'>
}
    

// Custom InputTypes
/**
 * DeliveryPricingTier without action
 */
export type DeliveryPricingTierDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the DeliveryPricingTier
   */
  select?: Prisma.DeliveryPricingTierSelect<ExtArgs> | null
  /**
   * Omit specific fields from the DeliveryPricingTier
   */
  omit?: Prisma.DeliveryPricingTierOmit<ExtArgs> | null
}
