
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `FinancialSettings` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model FinancialSettings
 * 
 */
export type FinancialSettingsModel = runtime.Types.Result.DefaultSelection<Prisma.$FinancialSettingsPayload>

export type AggregateFinancialSettings = {
  _count: FinancialSettingsCountAggregateOutputType | null
  _avg: FinancialSettingsAvgAggregateOutputType | null
  _sum: FinancialSettingsSumAggregateOutputType | null
  _min: FinancialSettingsMinAggregateOutputType | null
  _max: FinancialSettingsMaxAggregateOutputType | null
}

export type FinancialSettingsAvgAggregateOutputType = {
  defaultTipOptions: number | null
}

export type FinancialSettingsSumAggregateOutputType = {
  defaultTipOptions: number[]
}

export type FinancialSettingsMinAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  currency: string | null
  currencySymbol: string | null
  tipsEnabled: boolean | null
  tipType: string | null
  paymentProvider: string | null
  stripeEnabled: boolean | null
  stripeAccountId: string | null
  stripePublicKey: string | null
  stripeWebhookSecret: string | null
  stripeConnectStatus: string | null
  usePlatformAccountFallback: boolean | null
  mercadoPagoEnabled: boolean | null
  mercadoPagoAccessToken: string | null
  mercadoPagoPublicKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FinancialSettingsMaxAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  currency: string | null
  currencySymbol: string | null
  tipsEnabled: boolean | null
  tipType: string | null
  paymentProvider: string | null
  stripeEnabled: boolean | null
  stripeAccountId: string | null
  stripePublicKey: string | null
  stripeWebhookSecret: string | null
  stripeConnectStatus: string | null
  usePlatformAccountFallback: boolean | null
  mercadoPagoEnabled: boolean | null
  mercadoPagoAccessToken: string | null
  mercadoPagoPublicKey: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type FinancialSettingsCountAggregateOutputType = {
  id: number
  restaurantId: number
  currency: number
  currencySymbol: number
  tipsEnabled: number
  tipType: number
  defaultTipOptions: number
  paymentProvider: number
  paymentConfig: number
  stripeEnabled: number
  stripeAccountId: number
  stripePublicKey: number
  stripeWebhookSecret: number
  stripeConnectStatus: number
  stripeConnectDetails: number
  usePlatformAccountFallback: number
  mercadoPagoEnabled: number
  mercadoPagoAccessToken: number
  mercadoPagoPublicKey: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type FinancialSettingsAvgAggregateInputType = {
  defaultTipOptions?: true
}

export type FinancialSettingsSumAggregateInputType = {
  defaultTipOptions?: true
}

export type FinancialSettingsMinAggregateInputType = {
  id?: true
  restaurantId?: true
  currency?: true
  currencySymbol?: true
  tipsEnabled?: true
  tipType?: true
  paymentProvider?: true
  stripeEnabled?: true
  stripeAccountId?: true
  stripePublicKey?: true
  stripeWebhookSecret?: true
  stripeConnectStatus?: true
  usePlatformAccountFallback?: true
  mercadoPagoEnabled?: true
  mercadoPagoAccessToken?: true
  mercadoPagoPublicKey?: true
  createdAt?: true
  updatedAt?: true
}

export type FinancialSettingsMaxAggregateInputType = {
  id?: true
  restaurantId?: true
  currency?: true
  currencySymbol?: true
  tipsEnabled?: true
  tipType?: true
  paymentProvider?: true
  stripeEnabled?: true
  stripeAccountId?: true
  stripePublicKey?: true
  stripeWebhookSecret?: true
  stripeConnectStatus?: true
  usePlatformAccountFallback?: true
  mercadoPagoEnabled?: true
  mercadoPagoAccessToken?: true
  mercadoPagoPublicKey?: true
  createdAt?: true
  updatedAt?: true
}

export type FinancialSettingsCountAggregateInputType = {
  id?: true
  restaurantId?: true
  currency?: true
  currencySymbol?: true
  tipsEnabled?: true
  tipType?: true
  defaultTipOptions?: true
  paymentProvider?: true
  paymentConfig?: true
  stripeEnabled?: true
  stripeAccountId?: true
  stripePublicKey?: true
  stripeWebhookSecret?: true
  stripeConnectStatus?: true
  stripeConnectDetails?: true
  usePlatformAccountFallback?: true
  mercadoPagoEnabled?: true
  mercadoPagoAccessToken?: true
  mercadoPagoPublicKey?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type FinancialSettingsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FinancialSettings to aggregate.
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FinancialSettings to fetch.
   */
  orderBy?: Prisma.FinancialSettingsOrderByWithRelationInput | Prisma.FinancialSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.FinancialSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FinancialSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FinancialSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned FinancialSettings
  **/
  _count?: true | FinancialSettingsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: FinancialSettingsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: FinancialSettingsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: FinancialSettingsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: FinancialSettingsMaxAggregateInputType
}

export type GetFinancialSettingsAggregateType<T extends FinancialSettingsAggregateArgs> = {
      [P in keyof T & keyof AggregateFinancialSettings]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateFinancialSettings[P]>
    : Prisma.GetScalarType<T[P], AggregateFinancialSettings[P]>
}




export type FinancialSettingsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.FinancialSettingsWhereInput
  orderBy?: Prisma.FinancialSettingsOrderByWithAggregationInput | Prisma.FinancialSettingsOrderByWithAggregationInput[]
  by: Prisma.FinancialSettingsScalarFieldEnum[] | Prisma.FinancialSettingsScalarFieldEnum
  having?: Prisma.FinancialSettingsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: FinancialSettingsCountAggregateInputType | true
  _avg?: FinancialSettingsAvgAggregateInputType
  _sum?: FinancialSettingsSumAggregateInputType
  _min?: FinancialSettingsMinAggregateInputType
  _max?: FinancialSettingsMaxAggregateInputType
}

export type FinancialSettingsGroupByOutputType = {
  id: string
  restaurantId: string
  currency: string
  currencySymbol: string
  tipsEnabled: boolean
  tipType: string
  defaultTipOptions: number[]
  paymentProvider: string
  paymentConfig: runtime.JsonValue | null
  stripeEnabled: boolean
  stripeAccountId: string | null
  stripePublicKey: string | null
  stripeWebhookSecret: string | null
  stripeConnectStatus: string
  stripeConnectDetails: runtime.JsonValue | null
  usePlatformAccountFallback: boolean
  mercadoPagoEnabled: boolean
  mercadoPagoAccessToken: string | null
  mercadoPagoPublicKey: string | null
  createdAt: Date
  updatedAt: Date
  _count: FinancialSettingsCountAggregateOutputType | null
  _avg: FinancialSettingsAvgAggregateOutputType | null
  _sum: FinancialSettingsSumAggregateOutputType | null
  _min: FinancialSettingsMinAggregateOutputType | null
  _max: FinancialSettingsMaxAggregateOutputType | null
}

type GetFinancialSettingsGroupByPayload<T extends FinancialSettingsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<FinancialSettingsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof FinancialSettingsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], FinancialSettingsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], FinancialSettingsGroupByOutputType[P]>
      }
    >
  >



export type FinancialSettingsWhereInput = {
  AND?: Prisma.FinancialSettingsWhereInput | Prisma.FinancialSettingsWhereInput[]
  OR?: Prisma.FinancialSettingsWhereInput[]
  NOT?: Prisma.FinancialSettingsWhereInput | Prisma.FinancialSettingsWhereInput[]
  id?: Prisma.StringFilter<"FinancialSettings"> | string
  restaurantId?: Prisma.StringFilter<"FinancialSettings"> | string
  currency?: Prisma.StringFilter<"FinancialSettings"> | string
  currencySymbol?: Prisma.StringFilter<"FinancialSettings"> | string
  taxes?: Prisma.TaxSettingCompositeListFilter | Prisma.TaxSettingObjectEqualityInput[]
  tipsEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  tipType?: Prisma.StringFilter<"FinancialSettings"> | string
  defaultTipOptions?: Prisma.FloatNullableListFilter<"FinancialSettings">
  paymentProvider?: Prisma.StringFilter<"FinancialSettings"> | string
  paymentConfig?: Prisma.JsonNullableFilter<"FinancialSettings">
  stripeEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  stripeAccountId?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripePublicKey?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripeWebhookSecret?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripeConnectStatus?: Prisma.StringFilter<"FinancialSettings"> | string
  stripeConnectDetails?: Prisma.JsonNullableFilter<"FinancialSettings">
  usePlatformAccountFallback?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  mercadoPagoEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  mercadoPagoAccessToken?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  mercadoPagoPublicKey?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCompositeFilter, Prisma.GlobalFeeObjectEqualityInput> | null
  createdAt?: Prisma.DateTimeFilter<"FinancialSettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FinancialSettings"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}

export type FinancialSettingsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  taxes?: Prisma.TaxSettingOrderByCompositeAggregateInput
  tipsEnabled?: Prisma.SortOrder
  tipType?: Prisma.SortOrder
  defaultTipOptions?: Prisma.SortOrder
  paymentProvider?: Prisma.SortOrder
  paymentConfig?: Prisma.SortOrder
  stripeEnabled?: Prisma.SortOrder
  stripeAccountId?: Prisma.SortOrder
  stripePublicKey?: Prisma.SortOrder
  stripeWebhookSecret?: Prisma.SortOrder
  stripeConnectStatus?: Prisma.SortOrder
  stripeConnectDetails?: Prisma.SortOrder
  usePlatformAccountFallback?: Prisma.SortOrder
  mercadoPagoEnabled?: Prisma.SortOrder
  mercadoPagoAccessToken?: Prisma.SortOrder
  mercadoPagoPublicKey?: Prisma.SortOrder
  globalFee?: Prisma.GlobalFeeOrderByInput
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  restaurant?: Prisma.RestaurantOrderByWithRelationInput
}

export type FinancialSettingsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  restaurantId?: string
  AND?: Prisma.FinancialSettingsWhereInput | Prisma.FinancialSettingsWhereInput[]
  OR?: Prisma.FinancialSettingsWhereInput[]
  NOT?: Prisma.FinancialSettingsWhereInput | Prisma.FinancialSettingsWhereInput[]
  currency?: Prisma.StringFilter<"FinancialSettings"> | string
  currencySymbol?: Prisma.StringFilter<"FinancialSettings"> | string
  taxes?: Prisma.TaxSettingCompositeListFilter | Prisma.TaxSettingObjectEqualityInput[]
  tipsEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  tipType?: Prisma.StringFilter<"FinancialSettings"> | string
  defaultTipOptions?: Prisma.FloatNullableListFilter<"FinancialSettings">
  paymentProvider?: Prisma.StringFilter<"FinancialSettings"> | string
  paymentConfig?: Prisma.JsonNullableFilter<"FinancialSettings">
  stripeEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  stripeAccountId?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripePublicKey?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripeWebhookSecret?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  stripeConnectStatus?: Prisma.StringFilter<"FinancialSettings"> | string
  stripeConnectDetails?: Prisma.JsonNullableFilter<"FinancialSettings">
  usePlatformAccountFallback?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  mercadoPagoEnabled?: Prisma.BoolFilter<"FinancialSettings"> | boolean
  mercadoPagoAccessToken?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  mercadoPagoPublicKey?: Prisma.StringNullableFilter<"FinancialSettings"> | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCompositeFilter, Prisma.GlobalFeeObjectEqualityInput> | null
  createdAt?: Prisma.DateTimeFilter<"FinancialSettings"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"FinancialSettings"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}, "id" | "restaurantId">

export type FinancialSettingsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  tipsEnabled?: Prisma.SortOrder
  tipType?: Prisma.SortOrder
  defaultTipOptions?: Prisma.SortOrder
  paymentProvider?: Prisma.SortOrder
  paymentConfig?: Prisma.SortOrder
  stripeEnabled?: Prisma.SortOrder
  stripeAccountId?: Prisma.SortOrder
  stripePublicKey?: Prisma.SortOrder
  stripeWebhookSecret?: Prisma.SortOrder
  stripeConnectStatus?: Prisma.SortOrder
  stripeConnectDetails?: Prisma.SortOrder
  usePlatformAccountFallback?: Prisma.SortOrder
  mercadoPagoEnabled?: Prisma.SortOrder
  mercadoPagoAccessToken?: Prisma.SortOrder
  mercadoPagoPublicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.FinancialSettingsCountOrderByAggregateInput
  _avg?: Prisma.FinancialSettingsAvgOrderByAggregateInput
  _max?: Prisma.FinancialSettingsMaxOrderByAggregateInput
  _min?: Prisma.FinancialSettingsMinOrderByAggregateInput
  _sum?: Prisma.FinancialSettingsSumOrderByAggregateInput
}

export type FinancialSettingsScalarWhereWithAggregatesInput = {
  AND?: Prisma.FinancialSettingsScalarWhereWithAggregatesInput | Prisma.FinancialSettingsScalarWhereWithAggregatesInput[]
  OR?: Prisma.FinancialSettingsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.FinancialSettingsScalarWhereWithAggregatesInput | Prisma.FinancialSettingsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  restaurantId?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  currency?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  currencySymbol?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  tipsEnabled?: Prisma.BoolWithAggregatesFilter<"FinancialSettings"> | boolean
  tipType?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  defaultTipOptions?: Prisma.FloatNullableListFilter<"FinancialSettings">
  paymentProvider?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  paymentConfig?: Prisma.JsonNullableWithAggregatesFilter<"FinancialSettings">
  stripeEnabled?: Prisma.BoolWithAggregatesFilter<"FinancialSettings"> | boolean
  stripeAccountId?: Prisma.StringNullableWithAggregatesFilter<"FinancialSettings"> | string | null
  stripePublicKey?: Prisma.StringNullableWithAggregatesFilter<"FinancialSettings"> | string | null
  stripeWebhookSecret?: Prisma.StringNullableWithAggregatesFilter<"FinancialSettings"> | string | null
  stripeConnectStatus?: Prisma.StringWithAggregatesFilter<"FinancialSettings"> | string
  stripeConnectDetails?: Prisma.JsonNullableWithAggregatesFilter<"FinancialSettings">
  usePlatformAccountFallback?: Prisma.BoolWithAggregatesFilter<"FinancialSettings"> | boolean
  mercadoPagoEnabled?: Prisma.BoolWithAggregatesFilter<"FinancialSettings"> | boolean
  mercadoPagoAccessToken?: Prisma.StringNullableWithAggregatesFilter<"FinancialSettings"> | string | null
  mercadoPagoPublicKey?: Prisma.StringNullableWithAggregatesFilter<"FinancialSettings"> | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"FinancialSettings"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"FinancialSettings"> | Date | string
}

export type FinancialSettingsCreateInput = {
  id?: string
  currency?: string
  currencySymbol?: string
  taxes?: Prisma.XOR<Prisma.TaxSettingListCreateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: boolean
  tipType?: string
  defaultTipOptions?: Prisma.FinancialSettingsCreatedefaultTipOptionsInput | number[]
  paymentProvider?: string
  paymentConfig?: runtime.InputJsonValue | null
  stripeEnabled?: boolean
  stripeAccountId?: string | null
  stripePublicKey?: string | null
  stripeWebhookSecret?: string | null
  stripeConnectStatus?: string
  stripeConnectDetails?: runtime.InputJsonValue | null
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: string | null
  mercadoPagoPublicKey?: string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCreateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Date | string
  updatedAt?: Date | string
  restaurant: Prisma.RestaurantCreateNestedOneWithoutFinancialSettingsInput
}

export type FinancialSettingsUncheckedCreateInput = {
  id?: string
  restaurantId: string
  currency?: string
  currencySymbol?: string
  taxes?: Prisma.XOR<Prisma.TaxSettingListCreateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: boolean
  tipType?: string
  defaultTipOptions?: Prisma.FinancialSettingsCreatedefaultTipOptionsInput | number[]
  paymentProvider?: string
  paymentConfig?: runtime.InputJsonValue | null
  stripeEnabled?: boolean
  stripeAccountId?: string | null
  stripePublicKey?: string | null
  stripeWebhookSecret?: string | null
  stripeConnectStatus?: string
  stripeConnectDetails?: runtime.InputJsonValue | null
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: string | null
  mercadoPagoPublicKey?: string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCreateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinancialSettingsUpdateInput = {
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutFinancialSettingsNestedInput
}

export type FinancialSettingsUncheckedUpdateInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinancialSettingsCreateManyInput = {
  id?: string
  restaurantId: string
  currency?: string
  currencySymbol?: string
  taxes?: Prisma.XOR<Prisma.TaxSettingListCreateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: boolean
  tipType?: string
  defaultTipOptions?: Prisma.FinancialSettingsCreatedefaultTipOptionsInput | number[]
  paymentProvider?: string
  paymentConfig?: runtime.InputJsonValue | null
  stripeEnabled?: boolean
  stripeAccountId?: string | null
  stripePublicKey?: string | null
  stripeWebhookSecret?: string | null
  stripeConnectStatus?: string
  stripeConnectDetails?: runtime.InputJsonValue | null
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: string | null
  mercadoPagoPublicKey?: string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCreateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinancialSettingsUpdateManyMutationInput = {
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinancialSettingsUncheckedUpdateManyInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinancialSettingsNullableScalarRelationFilter = {
  is?: Prisma.FinancialSettingsWhereInput | null
  isNot?: Prisma.FinancialSettingsWhereInput | null
}

export type TaxSettingObjectEqualityInput = {
  name: string
  enabled: boolean
  rate: number
  type: string
  applyTo: string
}

export type FloatNullableListFilter<$PrismaModel = never> = {
  equals?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel> | null
  has?: number | Prisma.FloatFieldRefInput<$PrismaModel> | null
  hasEvery?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  hasSome?: number[] | Prisma.ListFloatFieldRefInput<$PrismaModel>
  isEmpty?: boolean
}

export type GlobalFeeObjectEqualityInput = {
  enabled: boolean
  threshold: number
  belowPercent: number
  aboveFlat: number
}

export type FinancialSettingsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  tipsEnabled?: Prisma.SortOrder
  tipType?: Prisma.SortOrder
  defaultTipOptions?: Prisma.SortOrder
  paymentProvider?: Prisma.SortOrder
  paymentConfig?: Prisma.SortOrder
  stripeEnabled?: Prisma.SortOrder
  stripeAccountId?: Prisma.SortOrder
  stripePublicKey?: Prisma.SortOrder
  stripeWebhookSecret?: Prisma.SortOrder
  stripeConnectStatus?: Prisma.SortOrder
  stripeConnectDetails?: Prisma.SortOrder
  usePlatformAccountFallback?: Prisma.SortOrder
  mercadoPagoEnabled?: Prisma.SortOrder
  mercadoPagoAccessToken?: Prisma.SortOrder
  mercadoPagoPublicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinancialSettingsAvgOrderByAggregateInput = {
  defaultTipOptions?: Prisma.SortOrder
}

export type FinancialSettingsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  tipsEnabled?: Prisma.SortOrder
  tipType?: Prisma.SortOrder
  paymentProvider?: Prisma.SortOrder
  stripeEnabled?: Prisma.SortOrder
  stripeAccountId?: Prisma.SortOrder
  stripePublicKey?: Prisma.SortOrder
  stripeWebhookSecret?: Prisma.SortOrder
  stripeConnectStatus?: Prisma.SortOrder
  usePlatformAccountFallback?: Prisma.SortOrder
  mercadoPagoEnabled?: Prisma.SortOrder
  mercadoPagoAccessToken?: Prisma.SortOrder
  mercadoPagoPublicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinancialSettingsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  currencySymbol?: Prisma.SortOrder
  tipsEnabled?: Prisma.SortOrder
  tipType?: Prisma.SortOrder
  paymentProvider?: Prisma.SortOrder
  stripeEnabled?: Prisma.SortOrder
  stripeAccountId?: Prisma.SortOrder
  stripePublicKey?: Prisma.SortOrder
  stripeWebhookSecret?: Prisma.SortOrder
  stripeConnectStatus?: Prisma.SortOrder
  usePlatformAccountFallback?: Prisma.SortOrder
  mercadoPagoEnabled?: Prisma.SortOrder
  mercadoPagoAccessToken?: Prisma.SortOrder
  mercadoPagoPublicKey?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type FinancialSettingsSumOrderByAggregateInput = {
  defaultTipOptions?: Prisma.SortOrder
}

export type FinancialSettingsCreateNestedOneWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
  connectOrCreate?: Prisma.FinancialSettingsCreateOrConnectWithoutRestaurantInput
  connect?: Prisma.FinancialSettingsWhereUniqueInput
}

export type FinancialSettingsUncheckedCreateNestedOneWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
  connectOrCreate?: Prisma.FinancialSettingsCreateOrConnectWithoutRestaurantInput
  connect?: Prisma.FinancialSettingsWhereUniqueInput
}

export type FinancialSettingsUpdateOneWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
  connectOrCreate?: Prisma.FinancialSettingsCreateOrConnectWithoutRestaurantInput
  upsert?: Prisma.FinancialSettingsUpsertWithoutRestaurantInput
  disconnect?: Prisma.FinancialSettingsWhereInput | boolean
  delete?: Prisma.FinancialSettingsWhereInput | boolean
  connect?: Prisma.FinancialSettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FinancialSettingsUpdateToOneWithWhereWithoutRestaurantInput, Prisma.FinancialSettingsUpdateWithoutRestaurantInput>, Prisma.FinancialSettingsUncheckedUpdateWithoutRestaurantInput>
}

export type FinancialSettingsUncheckedUpdateOneWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
  connectOrCreate?: Prisma.FinancialSettingsCreateOrConnectWithoutRestaurantInput
  upsert?: Prisma.FinancialSettingsUpsertWithoutRestaurantInput
  disconnect?: Prisma.FinancialSettingsWhereInput | boolean
  delete?: Prisma.FinancialSettingsWhereInput | boolean
  connect?: Prisma.FinancialSettingsWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.FinancialSettingsUpdateToOneWithWhereWithoutRestaurantInput, Prisma.FinancialSettingsUpdateWithoutRestaurantInput>, Prisma.FinancialSettingsUncheckedUpdateWithoutRestaurantInput>
}

export type TaxSettingCreateInput = {
  name: string
  enabled?: boolean
  rate: number
  type?: string
  applyTo?: string
}

export type FinancialSettingsCreatedefaultTipOptionsInput = {
  set: number[]
}

export type GlobalFeeCreateInput = {
  enabled?: boolean
  threshold?: number
  belowPercent?: number
  aboveFlat?: number
}

export type FinancialSettingsUpdatedefaultTipOptionsInput = {
  set?: number[]
  push?: number | number[]
}

export type FinancialSettingsCreateWithoutRestaurantInput = {
  id?: string
  currency?: string
  currencySymbol?: string
  taxes?: Prisma.XOR<Prisma.TaxSettingListCreateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: boolean
  tipType?: string
  defaultTipOptions?: Prisma.FinancialSettingsCreatedefaultTipOptionsInput | number[]
  paymentProvider?: string
  paymentConfig?: runtime.InputJsonValue | null
  stripeEnabled?: boolean
  stripeAccountId?: string | null
  stripePublicKey?: string | null
  stripeWebhookSecret?: string | null
  stripeConnectStatus?: string
  stripeConnectDetails?: runtime.InputJsonValue | null
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: string | null
  mercadoPagoPublicKey?: string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCreateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinancialSettingsUncheckedCreateWithoutRestaurantInput = {
  id?: string
  currency?: string
  currencySymbol?: string
  taxes?: Prisma.XOR<Prisma.TaxSettingListCreateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: boolean
  tipType?: string
  defaultTipOptions?: Prisma.FinancialSettingsCreatedefaultTipOptionsInput | number[]
  paymentProvider?: string
  paymentConfig?: runtime.InputJsonValue | null
  stripeEnabled?: boolean
  stripeAccountId?: string | null
  stripePublicKey?: string | null
  stripeWebhookSecret?: string | null
  stripeConnectStatus?: string
  stripeConnectDetails?: runtime.InputJsonValue | null
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: string | null
  mercadoPagoPublicKey?: string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableCreateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type FinancialSettingsCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.FinancialSettingsWhereUniqueInput
  create: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
}

export type FinancialSettingsUpsertWithoutRestaurantInput = {
  update: Prisma.XOR<Prisma.FinancialSettingsUpdateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedUpdateWithoutRestaurantInput>
  create: Prisma.XOR<Prisma.FinancialSettingsCreateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedCreateWithoutRestaurantInput>
  where?: Prisma.FinancialSettingsWhereInput
}

export type FinancialSettingsUpdateToOneWithWhereWithoutRestaurantInput = {
  where?: Prisma.FinancialSettingsWhereInput
  data: Prisma.XOR<Prisma.FinancialSettingsUpdateWithoutRestaurantInput, Prisma.FinancialSettingsUncheckedUpdateWithoutRestaurantInput>
}

export type FinancialSettingsUpdateWithoutRestaurantInput = {
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type FinancialSettingsUncheckedUpdateWithoutRestaurantInput = {
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  currencySymbol?: Prisma.StringFieldUpdateOperationsInput | string
  taxes?: Prisma.XOR<Prisma.TaxSettingListUpdateEnvelopeInput, Prisma.TaxSettingCreateInput> | Prisma.TaxSettingCreateInput[]
  tipsEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  tipType?: Prisma.StringFieldUpdateOperationsInput | string
  defaultTipOptions?: Prisma.FinancialSettingsUpdatedefaultTipOptionsInput | number[]
  paymentProvider?: Prisma.StringFieldUpdateOperationsInput | string
  paymentConfig?: runtime.InputJsonValue | runtime.InputJsonValue | null
  stripeEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  stripeAccountId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripePublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeWebhookSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  stripeConnectStatus?: Prisma.StringFieldUpdateOperationsInput | string
  stripeConnectDetails?: runtime.InputJsonValue | runtime.InputJsonValue | null
  usePlatformAccountFallback?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  mercadoPagoAccessToken?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  mercadoPagoPublicKey?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  globalFee?: Prisma.XOR<Prisma.GlobalFeeNullableUpdateEnvelopeInput, Prisma.GlobalFeeCreateInput> | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type FinancialSettingsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  restaurantId?: boolean
  currency?: boolean
  currencySymbol?: boolean
  taxes?: boolean | Prisma.TaxSettingDefaultArgs<ExtArgs>
  tipsEnabled?: boolean
  tipType?: boolean
  defaultTipOptions?: boolean
  paymentProvider?: boolean
  paymentConfig?: boolean
  stripeEnabled?: boolean
  stripeAccountId?: boolean
  stripePublicKey?: boolean
  stripeWebhookSecret?: boolean
  stripeConnectStatus?: boolean
  stripeConnectDetails?: boolean
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: boolean
  mercadoPagoPublicKey?: boolean
  globalFee?: boolean | Prisma.GlobalFeeDefaultArgs<ExtArgs>
  createdAt?: boolean
  updatedAt?: boolean
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["financialSettings"]>



export type FinancialSettingsSelectScalar = {
  id?: boolean
  restaurantId?: boolean
  currency?: boolean
  currencySymbol?: boolean
  tipsEnabled?: boolean
  tipType?: boolean
  defaultTipOptions?: boolean
  paymentProvider?: boolean
  paymentConfig?: boolean
  stripeEnabled?: boolean
  stripeAccountId?: boolean
  stripePublicKey?: boolean
  stripeWebhookSecret?: boolean
  stripeConnectStatus?: boolean
  stripeConnectDetails?: boolean
  usePlatformAccountFallback?: boolean
  mercadoPagoEnabled?: boolean
  mercadoPagoAccessToken?: boolean
  mercadoPagoPublicKey?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type FinancialSettingsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "restaurantId" | "currency" | "currencySymbol" | "taxes" | "tipsEnabled" | "tipType" | "defaultTipOptions" | "paymentProvider" | "paymentConfig" | "stripeEnabled" | "stripeAccountId" | "stripePublicKey" | "stripeWebhookSecret" | "stripeConnectStatus" | "stripeConnectDetails" | "usePlatformAccountFallback" | "mercadoPagoEnabled" | "mercadoPagoAccessToken" | "mercadoPagoPublicKey" | "globalFee" | "createdAt" | "updatedAt", ExtArgs["result"]["financialSettings"]>
export type FinancialSettingsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}

export type $FinancialSettingsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "FinancialSettings"
  objects: {
    restaurant: Prisma.$RestaurantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    restaurantId: string
    currency: string
    currencySymbol: string
    tipsEnabled: boolean
    tipType: string
    defaultTipOptions: number[]
    paymentProvider: string
    paymentConfig: runtime.JsonValue | null
    stripeEnabled: boolean
    stripeAccountId: string | null
    stripePublicKey: string | null
    stripeWebhookSecret: string | null
    stripeConnectStatus: string
    stripeConnectDetails: runtime.JsonValue | null
    usePlatformAccountFallback: boolean
    mercadoPagoEnabled: boolean
    mercadoPagoAccessToken: string | null
    mercadoPagoPublicKey: string | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["financialSettings"]>
  composites: {
    taxes: Prisma.$TaxSettingPayload[]
    globalFee: Prisma.$GlobalFeePayload | null
  }
}

export type FinancialSettingsGetPayload<S extends boolean | null | undefined | FinancialSettingsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload, S>

export type FinancialSettingsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<FinancialSettingsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: FinancialSettingsCountAggregateInputType | true
  }

export interface FinancialSettingsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['FinancialSettings'], meta: { name: 'FinancialSettings' } }
  /**
   * Find zero or one FinancialSettings that matches the filter.
   * @param {FinancialSettingsFindUniqueArgs} args - Arguments to find a FinancialSettings
   * @example
   * // Get one FinancialSettings
   * const financialSettings = await prisma.financialSettings.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends FinancialSettingsFindUniqueArgs>(args: Prisma.SelectSubset<T, FinancialSettingsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one FinancialSettings that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {FinancialSettingsFindUniqueOrThrowArgs} args - Arguments to find a FinancialSettings
   * @example
   * // Get one FinancialSettings
   * const financialSettings = await prisma.financialSettings.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends FinancialSettingsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, FinancialSettingsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FinancialSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsFindFirstArgs} args - Arguments to find a FinancialSettings
   * @example
   * // Get one FinancialSettings
   * const financialSettings = await prisma.financialSettings.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends FinancialSettingsFindFirstArgs>(args?: Prisma.SelectSubset<T, FinancialSettingsFindFirstArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first FinancialSettings that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsFindFirstOrThrowArgs} args - Arguments to find a FinancialSettings
   * @example
   * // Get one FinancialSettings
   * const financialSettings = await prisma.financialSettings.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends FinancialSettingsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, FinancialSettingsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FinancialSettings that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all FinancialSettings
   * const financialSettings = await prisma.financialSettings.findMany()
   * 
   * // Get first 10 FinancialSettings
   * const financialSettings = await prisma.financialSettings.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const financialSettingsWithIdOnly = await prisma.financialSettings.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends FinancialSettingsFindManyArgs>(args?: Prisma.SelectSubset<T, FinancialSettingsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a FinancialSettings.
   * @param {FinancialSettingsCreateArgs} args - Arguments to create a FinancialSettings.
   * @example
   * // Create one FinancialSettings
   * const FinancialSettings = await prisma.financialSettings.create({
   *   data: {
   *     // ... data to create a FinancialSettings
   *   }
   * })
   * 
   */
  create<T extends FinancialSettingsCreateArgs>(args: Prisma.SelectSubset<T, FinancialSettingsCreateArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many FinancialSettings.
   * @param {FinancialSettingsCreateManyArgs} args - Arguments to create many FinancialSettings.
   * @example
   * // Create many FinancialSettings
   * const financialSettings = await prisma.financialSettings.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends FinancialSettingsCreateManyArgs>(args?: Prisma.SelectSubset<T, FinancialSettingsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a FinancialSettings.
   * @param {FinancialSettingsDeleteArgs} args - Arguments to delete one FinancialSettings.
   * @example
   * // Delete one FinancialSettings
   * const FinancialSettings = await prisma.financialSettings.delete({
   *   where: {
   *     // ... filter to delete one FinancialSettings
   *   }
   * })
   * 
   */
  delete<T extends FinancialSettingsDeleteArgs>(args: Prisma.SelectSubset<T, FinancialSettingsDeleteArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one FinancialSettings.
   * @param {FinancialSettingsUpdateArgs} args - Arguments to update one FinancialSettings.
   * @example
   * // Update one FinancialSettings
   * const financialSettings = await prisma.financialSettings.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends FinancialSettingsUpdateArgs>(args: Prisma.SelectSubset<T, FinancialSettingsUpdateArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more FinancialSettings.
   * @param {FinancialSettingsDeleteManyArgs} args - Arguments to filter FinancialSettings to delete.
   * @example
   * // Delete a few FinancialSettings
   * const { count } = await prisma.financialSettings.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends FinancialSettingsDeleteManyArgs>(args?: Prisma.SelectSubset<T, FinancialSettingsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more FinancialSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many FinancialSettings
   * const financialSettings = await prisma.financialSettings.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends FinancialSettingsUpdateManyArgs>(args: Prisma.SelectSubset<T, FinancialSettingsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one FinancialSettings.
   * @param {FinancialSettingsUpsertArgs} args - Arguments to update or create a FinancialSettings.
   * @example
   * // Update or create a FinancialSettings
   * const financialSettings = await prisma.financialSettings.upsert({
   *   create: {
   *     // ... data to create a FinancialSettings
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the FinancialSettings we want to update
   *   }
   * })
   */
  upsert<T extends FinancialSettingsUpsertArgs>(args: Prisma.SelectSubset<T, FinancialSettingsUpsertArgs<ExtArgs>>): Prisma.Prisma__FinancialSettingsClient<runtime.Types.Result.GetResult<Prisma.$FinancialSettingsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more FinancialSettings that matches the filter.
   * @param {FinancialSettingsFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const financialSettings = await prisma.financialSettings.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.FinancialSettingsFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a FinancialSettings.
   * @param {FinancialSettingsAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const financialSettings = await prisma.financialSettings.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.FinancialSettingsAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of FinancialSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsCountArgs} args - Arguments to filter FinancialSettings to count.
   * @example
   * // Count the number of FinancialSettings
   * const count = await prisma.financialSettings.count({
   *   where: {
   *     // ... the filter for the FinancialSettings we want to count
   *   }
   * })
  **/
  count<T extends FinancialSettingsCountArgs>(
    args?: Prisma.Subset<T, FinancialSettingsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], FinancialSettingsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a FinancialSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends FinancialSettingsAggregateArgs>(args: Prisma.Subset<T, FinancialSettingsAggregateArgs>): Prisma.PrismaPromise<GetFinancialSettingsAggregateType<T>>

  /**
   * Group by FinancialSettings.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {FinancialSettingsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends FinancialSettingsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: FinancialSettingsGroupByArgs['orderBy'] }
      : { orderBy?: FinancialSettingsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, FinancialSettingsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetFinancialSettingsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the FinancialSettings model
 */
readonly fields: FinancialSettingsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for FinancialSettings.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__FinancialSettingsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>): Prisma.Prisma__RestaurantClient<runtime.Types.Result.GetResult<Prisma.$RestaurantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the FinancialSettings model
 */
export interface FinancialSettingsFieldRefs {
  readonly id: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly restaurantId: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly currency: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly currencySymbol: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly tipsEnabled: Prisma.FieldRef<"FinancialSettings", 'Boolean'>
  readonly tipType: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly defaultTipOptions: Prisma.FieldRef<"FinancialSettings", 'Float[]'>
  readonly paymentProvider: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly paymentConfig: Prisma.FieldRef<"FinancialSettings", 'Json'>
  readonly stripeEnabled: Prisma.FieldRef<"FinancialSettings", 'Boolean'>
  readonly stripeAccountId: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly stripePublicKey: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly stripeWebhookSecret: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly stripeConnectStatus: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly stripeConnectDetails: Prisma.FieldRef<"FinancialSettings", 'Json'>
  readonly usePlatformAccountFallback: Prisma.FieldRef<"FinancialSettings", 'Boolean'>
  readonly mercadoPagoEnabled: Prisma.FieldRef<"FinancialSettings", 'Boolean'>
  readonly mercadoPagoAccessToken: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly mercadoPagoPublicKey: Prisma.FieldRef<"FinancialSettings", 'String'>
  readonly createdAt: Prisma.FieldRef<"FinancialSettings", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"FinancialSettings", 'DateTime'>
}
    

// Custom InputTypes
/**
 * FinancialSettings findUnique
 */
export type FinancialSettingsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter, which FinancialSettings to fetch.
   */
  where: Prisma.FinancialSettingsWhereUniqueInput
}

/**
 * FinancialSettings findUniqueOrThrow
 */
export type FinancialSettingsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter, which FinancialSettings to fetch.
   */
  where: Prisma.FinancialSettingsWhereUniqueInput
}

/**
 * FinancialSettings findFirst
 */
export type FinancialSettingsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter, which FinancialSettings to fetch.
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FinancialSettings to fetch.
   */
  orderBy?: Prisma.FinancialSettingsOrderByWithRelationInput | Prisma.FinancialSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FinancialSettings.
   */
  cursor?: Prisma.FinancialSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FinancialSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FinancialSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FinancialSettings.
   */
  distinct?: Prisma.FinancialSettingsScalarFieldEnum | Prisma.FinancialSettingsScalarFieldEnum[]
}

/**
 * FinancialSettings findFirstOrThrow
 */
export type FinancialSettingsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter, which FinancialSettings to fetch.
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FinancialSettings to fetch.
   */
  orderBy?: Prisma.FinancialSettingsOrderByWithRelationInput | Prisma.FinancialSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for FinancialSettings.
   */
  cursor?: Prisma.FinancialSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FinancialSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FinancialSettings.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of FinancialSettings.
   */
  distinct?: Prisma.FinancialSettingsScalarFieldEnum | Prisma.FinancialSettingsScalarFieldEnum[]
}

/**
 * FinancialSettings findMany
 */
export type FinancialSettingsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter, which FinancialSettings to fetch.
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of FinancialSettings to fetch.
   */
  orderBy?: Prisma.FinancialSettingsOrderByWithRelationInput | Prisma.FinancialSettingsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing FinancialSettings.
   */
  cursor?: Prisma.FinancialSettingsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` FinancialSettings from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` FinancialSettings.
   */
  skip?: number
  distinct?: Prisma.FinancialSettingsScalarFieldEnum | Prisma.FinancialSettingsScalarFieldEnum[]
}

/**
 * FinancialSettings create
 */
export type FinancialSettingsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * The data needed to create a FinancialSettings.
   */
  data: Prisma.XOR<Prisma.FinancialSettingsCreateInput, Prisma.FinancialSettingsUncheckedCreateInput>
}

/**
 * FinancialSettings createMany
 */
export type FinancialSettingsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many FinancialSettings.
   */
  data: Prisma.FinancialSettingsCreateManyInput | Prisma.FinancialSettingsCreateManyInput[]
}

/**
 * FinancialSettings update
 */
export type FinancialSettingsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * The data needed to update a FinancialSettings.
   */
  data: Prisma.XOR<Prisma.FinancialSettingsUpdateInput, Prisma.FinancialSettingsUncheckedUpdateInput>
  /**
   * Choose, which FinancialSettings to update.
   */
  where: Prisma.FinancialSettingsWhereUniqueInput
}

/**
 * FinancialSettings updateMany
 */
export type FinancialSettingsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update FinancialSettings.
   */
  data: Prisma.XOR<Prisma.FinancialSettingsUpdateManyMutationInput, Prisma.FinancialSettingsUncheckedUpdateManyInput>
  /**
   * Filter which FinancialSettings to update
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * Limit how many FinancialSettings to update.
   */
  limit?: number
}

/**
 * FinancialSettings upsert
 */
export type FinancialSettingsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * The filter to search for the FinancialSettings to update in case it exists.
   */
  where: Prisma.FinancialSettingsWhereUniqueInput
  /**
   * In case the FinancialSettings found by the `where` argument doesn't exist, create a new FinancialSettings with this data.
   */
  create: Prisma.XOR<Prisma.FinancialSettingsCreateInput, Prisma.FinancialSettingsUncheckedCreateInput>
  /**
   * In case the FinancialSettings was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.FinancialSettingsUpdateInput, Prisma.FinancialSettingsUncheckedUpdateInput>
}

/**
 * FinancialSettings delete
 */
export type FinancialSettingsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
  /**
   * Filter which FinancialSettings to delete.
   */
  where: Prisma.FinancialSettingsWhereUniqueInput
}

/**
 * FinancialSettings deleteMany
 */
export type FinancialSettingsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which FinancialSettings to delete
   */
  where?: Prisma.FinancialSettingsWhereInput
  /**
   * Limit how many FinancialSettings to delete.
   */
  limit?: number
}

/**
 * FinancialSettings findRaw
 */
export type FinancialSettingsFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * FinancialSettings aggregateRaw
 */
export type FinancialSettingsAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * FinancialSettings without action
 */
export type FinancialSettingsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the FinancialSettings
   */
  select?: Prisma.FinancialSettingsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the FinancialSettings
   */
  omit?: Prisma.FinancialSettingsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.FinancialSettingsInclude<ExtArgs> | null
}
