
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `ItemFee` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model ItemFee
 * 
 */
export type ItemFeeModel = runtime.Types.Result.DefaultSelection<Prisma.$ItemFeePayload>






export type ItemFeeCompositeListFilter = {
  equals?: Prisma.ItemFeeObjectEqualityInput[]
  every?: Prisma.ItemFeeWhereInput
  some?: Prisma.ItemFeeWhereInput
  none?: Prisma.ItemFeeWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type ItemFeeOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ItemFeeListCreateEnvelopeInput = {
  set?: Prisma.ItemFeeCreateInput | Prisma.ItemFeeCreateInput[]
}

export type ItemFeeListUpdateEnvelopeInput = {
  set?: Prisma.ItemFeeCreateInput | Prisma.ItemFeeCreateInput[]
  push?: Prisma.ItemFeeCreateInput | Prisma.ItemFeeCreateInput[]
  updateMany?: Prisma.ItemFeeUpdateManyInput
  deleteMany?: Prisma.ItemFeeDeleteManyInput
}

export type ItemFeeWhereInput = {
  AND?: Prisma.ItemFeeWhereInput | Prisma.ItemFeeWhereInput[]
  OR?: Prisma.ItemFeeWhereInput[]
  NOT?: Prisma.ItemFeeWhereInput | Prisma.ItemFeeWhereInput[]
  name?: Prisma.StringFilter<"ItemFee"> | string
  price?: Prisma.FloatFilter<"ItemFee"> | number
}

export type ItemFeeUpdateManyInput = {
  where: Prisma.ItemFeeWhereInput
  data: Prisma.ItemFeeUpdateInput
}

export type ItemFeeDeleteManyInput = {
  where: Prisma.ItemFeeWhereInput
}

export type ItemFeeUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type ItemFeeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  price?: boolean
}, ExtArgs["result"]["itemFee"]>



export type ItemFeeSelectScalar = {
  name?: boolean
  price?: boolean
}

export type ItemFeeOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "price", ExtArgs["result"]["itemFee"]>

export type $ItemFeePayload = {
  name: "ItemFee"
  objects: {}
  scalars: {
    name: string
    price: number
  }
  composites: {}
}

export type ItemFeeGetPayload<S extends boolean | null | undefined | ItemFeeDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ItemFeePayload, S>





/**
 * Fields of the ItemFee model
 */
export interface ItemFeeFieldRefs {
  readonly name: Prisma.FieldRef<"ItemFee", 'String'>
  readonly price: Prisma.FieldRef<"ItemFee", 'Float'>
}
    

// Custom InputTypes
/**
 * ItemFee without action
 */
export type ItemFeeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ItemFee
   */
  select?: Prisma.ItemFeeSelect<ExtArgs> | null
  /**
   * Omit specific fields from the ItemFee
   */
  omit?: Prisma.ItemFeeOmit<ExtArgs> | null
}
