
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `KitchenStage` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model KitchenStage
 * 
 */
export type KitchenStageModel = runtime.Types.Result.DefaultSelection<Prisma.$KitchenStagePayload>

export type AggregateKitchenStage = {
  _count: KitchenStageCountAggregateOutputType | null
  _avg: KitchenStageAvgAggregateOutputType | null
  _sum: KitchenStageSumAggregateOutputType | null
  _min: KitchenStageMinAggregateOutputType | null
  _max: KitchenStageMaxAggregateOutputType | null
}

export type KitchenStageAvgAggregateOutputType = {
  order: number | null
}

export type KitchenStageSumAggregateOutputType = {
  order: number | null
}

export type KitchenStageMinAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  status: string | null
  displayName: string | null
  color: string | null
  order: number | null
  isEnabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KitchenStageMaxAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  status: string | null
  displayName: string | null
  color: string | null
  order: number | null
  isEnabled: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type KitchenStageCountAggregateOutputType = {
  id: number
  restaurantId: number
  status: number
  displayName: number
  color: number
  order: number
  isEnabled: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type KitchenStageAvgAggregateInputType = {
  order?: true
}

export type KitchenStageSumAggregateInputType = {
  order?: true
}

export type KitchenStageMinAggregateInputType = {
  id?: true
  restaurantId?: true
  status?: true
  displayName?: true
  color?: true
  order?: true
  isEnabled?: true
  createdAt?: true
  updatedAt?: true
}

export type KitchenStageMaxAggregateInputType = {
  id?: true
  restaurantId?: true
  status?: true
  displayName?: true
  color?: true
  order?: true
  isEnabled?: true
  createdAt?: true
  updatedAt?: true
}

export type KitchenStageCountAggregateInputType = {
  id?: true
  restaurantId?: true
  status?: true
  displayName?: true
  color?: true
  order?: true
  isEnabled?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type KitchenStageAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KitchenStage to aggregate.
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KitchenStages to fetch.
   */
  orderBy?: Prisma.KitchenStageOrderByWithRelationInput | Prisma.KitchenStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.KitchenStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KitchenStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KitchenStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned KitchenStages
  **/
  _count?: true | KitchenStageCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: KitchenStageAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: KitchenStageSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: KitchenStageMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: KitchenStageMaxAggregateInputType
}

export type GetKitchenStageAggregateType<T extends KitchenStageAggregateArgs> = {
      [P in keyof T & keyof AggregateKitchenStage]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateKitchenStage[P]>
    : Prisma.GetScalarType<T[P], AggregateKitchenStage[P]>
}




export type KitchenStageGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.KitchenStageWhereInput
  orderBy?: Prisma.KitchenStageOrderByWithAggregationInput | Prisma.KitchenStageOrderByWithAggregationInput[]
  by: Prisma.KitchenStageScalarFieldEnum[] | Prisma.KitchenStageScalarFieldEnum
  having?: Prisma.KitchenStageScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: KitchenStageCountAggregateInputType | true
  _avg?: KitchenStageAvgAggregateInputType
  _sum?: KitchenStageSumAggregateInputType
  _min?: KitchenStageMinAggregateInputType
  _max?: KitchenStageMaxAggregateInputType
}

export type KitchenStageGroupByOutputType = {
  id: string
  restaurantId: string
  status: string
  displayName: string
  color: string
  order: number
  isEnabled: boolean
  createdAt: Date
  updatedAt: Date
  _count: KitchenStageCountAggregateOutputType | null
  _avg: KitchenStageAvgAggregateOutputType | null
  _sum: KitchenStageSumAggregateOutputType | null
  _min: KitchenStageMinAggregateOutputType | null
  _max: KitchenStageMaxAggregateOutputType | null
}

type GetKitchenStageGroupByPayload<T extends KitchenStageGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<KitchenStageGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof KitchenStageGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], KitchenStageGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], KitchenStageGroupByOutputType[P]>
      }
    >
  >



export type KitchenStageWhereInput = {
  AND?: Prisma.KitchenStageWhereInput | Prisma.KitchenStageWhereInput[]
  OR?: Prisma.KitchenStageWhereInput[]
  NOT?: Prisma.KitchenStageWhereInput | Prisma.KitchenStageWhereInput[]
  id?: Prisma.StringFilter<"KitchenStage"> | string
  restaurantId?: Prisma.StringFilter<"KitchenStage"> | string
  status?: Prisma.StringFilter<"KitchenStage"> | string
  displayName?: Prisma.StringFilter<"KitchenStage"> | string
  color?: Prisma.StringFilter<"KitchenStage"> | string
  order?: Prisma.IntFilter<"KitchenStage"> | number
  isEnabled?: Prisma.BoolFilter<"KitchenStage"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}

export type KitchenStageOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  color?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  restaurant?: Prisma.RestaurantOrderByWithRelationInput
}

export type KitchenStageWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  restaurantId_status?: Prisma.KitchenStageRestaurantIdStatusCompoundUniqueInput
  AND?: Prisma.KitchenStageWhereInput | Prisma.KitchenStageWhereInput[]
  OR?: Prisma.KitchenStageWhereInput[]
  NOT?: Prisma.KitchenStageWhereInput | Prisma.KitchenStageWhereInput[]
  restaurantId?: Prisma.StringFilter<"KitchenStage"> | string
  status?: Prisma.StringFilter<"KitchenStage"> | string
  displayName?: Prisma.StringFilter<"KitchenStage"> | string
  color?: Prisma.StringFilter<"KitchenStage"> | string
  order?: Prisma.IntFilter<"KitchenStage"> | number
  isEnabled?: Prisma.BoolFilter<"KitchenStage"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}, "id" | "restaurantId_status">

export type KitchenStageOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  color?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.KitchenStageCountOrderByAggregateInput
  _avg?: Prisma.KitchenStageAvgOrderByAggregateInput
  _max?: Prisma.KitchenStageMaxOrderByAggregateInput
  _min?: Prisma.KitchenStageMinOrderByAggregateInput
  _sum?: Prisma.KitchenStageSumOrderByAggregateInput
}

export type KitchenStageScalarWhereWithAggregatesInput = {
  AND?: Prisma.KitchenStageScalarWhereWithAggregatesInput | Prisma.KitchenStageScalarWhereWithAggregatesInput[]
  OR?: Prisma.KitchenStageScalarWhereWithAggregatesInput[]
  NOT?: Prisma.KitchenStageScalarWhereWithAggregatesInput | Prisma.KitchenStageScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"KitchenStage"> | string
  restaurantId?: Prisma.StringWithAggregatesFilter<"KitchenStage"> | string
  status?: Prisma.StringWithAggregatesFilter<"KitchenStage"> | string
  displayName?: Prisma.StringWithAggregatesFilter<"KitchenStage"> | string
  color?: Prisma.StringWithAggregatesFilter<"KitchenStage"> | string
  order?: Prisma.IntWithAggregatesFilter<"KitchenStage"> | number
  isEnabled?: Prisma.BoolWithAggregatesFilter<"KitchenStage"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"KitchenStage"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"KitchenStage"> | Date | string
}

export type KitchenStageCreateInput = {
  id?: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  restaurant: Prisma.RestaurantCreateNestedOneWithoutKitchenStagesInput
}

export type KitchenStageUncheckedCreateInput = {
  id?: string
  restaurantId: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitchenStageUpdateInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutKitchenStagesNestedInput
}

export type KitchenStageUncheckedUpdateInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitchenStageCreateManyInput = {
  id?: string
  restaurantId: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitchenStageUpdateManyMutationInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitchenStageUncheckedUpdateManyInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitchenStageRestaurantIdStatusCompoundUniqueInput = {
  restaurantId: string
  status: string
}

export type KitchenStageCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  color?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitchenStageAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type KitchenStageMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  color?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitchenStageMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  displayName?: Prisma.SortOrder
  color?: Prisma.SortOrder
  order?: Prisma.SortOrder
  isEnabled?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type KitchenStageSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type KitchenStageListRelationFilter = {
  every?: Prisma.KitchenStageWhereInput
  some?: Prisma.KitchenStageWhereInput
  none?: Prisma.KitchenStageWhereInput
}

export type KitchenStageOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type StringFieldUpdateOperationsInput = {
  set?: string
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type BoolFieldUpdateOperationsInput = {
  set?: boolean
}

export type DateTimeFieldUpdateOperationsInput = {
  set?: Date | string
}

export type KitchenStageCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput> | Prisma.KitchenStageCreateWithoutRestaurantInput[] | Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput | Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.KitchenStageCreateManyRestaurantInputEnvelope
  connect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
}

export type KitchenStageUncheckedCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput> | Prisma.KitchenStageCreateWithoutRestaurantInput[] | Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput | Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.KitchenStageCreateManyRestaurantInputEnvelope
  connect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
}

export type KitchenStageUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput> | Prisma.KitchenStageCreateWithoutRestaurantInput[] | Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput | Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.KitchenStageUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.KitchenStageUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.KitchenStageCreateManyRestaurantInputEnvelope
  set?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  disconnect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  delete?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  connect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  update?: Prisma.KitchenStageUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.KitchenStageUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.KitchenStageUpdateManyWithWhereWithoutRestaurantInput | Prisma.KitchenStageUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.KitchenStageScalarWhereInput | Prisma.KitchenStageScalarWhereInput[]
}

export type KitchenStageUncheckedUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput> | Prisma.KitchenStageCreateWithoutRestaurantInput[] | Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput | Prisma.KitchenStageCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.KitchenStageUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.KitchenStageUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.KitchenStageCreateManyRestaurantInputEnvelope
  set?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  disconnect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  delete?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  connect?: Prisma.KitchenStageWhereUniqueInput | Prisma.KitchenStageWhereUniqueInput[]
  update?: Prisma.KitchenStageUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.KitchenStageUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.KitchenStageUpdateManyWithWhereWithoutRestaurantInput | Prisma.KitchenStageUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.KitchenStageScalarWhereInput | Prisma.KitchenStageScalarWhereInput[]
}

export type KitchenStageCreateWithoutRestaurantInput = {
  id?: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitchenStageUncheckedCreateWithoutRestaurantInput = {
  id?: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitchenStageCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.KitchenStageWhereUniqueInput
  create: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput>
}

export type KitchenStageCreateManyRestaurantInputEnvelope = {
  data: Prisma.KitchenStageCreateManyRestaurantInput | Prisma.KitchenStageCreateManyRestaurantInput[]
}

export type KitchenStageUpsertWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.KitchenStageWhereUniqueInput
  update: Prisma.XOR<Prisma.KitchenStageUpdateWithoutRestaurantInput, Prisma.KitchenStageUncheckedUpdateWithoutRestaurantInput>
  create: Prisma.XOR<Prisma.KitchenStageCreateWithoutRestaurantInput, Prisma.KitchenStageUncheckedCreateWithoutRestaurantInput>
}

export type KitchenStageUpdateWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.KitchenStageWhereUniqueInput
  data: Prisma.XOR<Prisma.KitchenStageUpdateWithoutRestaurantInput, Prisma.KitchenStageUncheckedUpdateWithoutRestaurantInput>
}

export type KitchenStageUpdateManyWithWhereWithoutRestaurantInput = {
  where: Prisma.KitchenStageScalarWhereInput
  data: Prisma.XOR<Prisma.KitchenStageUpdateManyMutationInput, Prisma.KitchenStageUncheckedUpdateManyWithoutRestaurantInput>
}

export type KitchenStageScalarWhereInput = {
  AND?: Prisma.KitchenStageScalarWhereInput | Prisma.KitchenStageScalarWhereInput[]
  OR?: Prisma.KitchenStageScalarWhereInput[]
  NOT?: Prisma.KitchenStageScalarWhereInput | Prisma.KitchenStageScalarWhereInput[]
  id?: Prisma.StringFilter<"KitchenStage"> | string
  restaurantId?: Prisma.StringFilter<"KitchenStage"> | string
  status?: Prisma.StringFilter<"KitchenStage"> | string
  displayName?: Prisma.StringFilter<"KitchenStage"> | string
  color?: Prisma.StringFilter<"KitchenStage"> | string
  order?: Prisma.IntFilter<"KitchenStage"> | number
  isEnabled?: Prisma.BoolFilter<"KitchenStage"> | boolean
  createdAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"KitchenStage"> | Date | string
}

export type KitchenStageCreateManyRestaurantInput = {
  id?: string
  status: string
  displayName: string
  color?: string
  order?: number
  isEnabled?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type KitchenStageUpdateWithoutRestaurantInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitchenStageUncheckedUpdateWithoutRestaurantInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type KitchenStageUncheckedUpdateManyWithoutRestaurantInput = {
  status?: Prisma.StringFieldUpdateOperationsInput | string
  displayName?: Prisma.StringFieldUpdateOperationsInput | string
  color?: Prisma.StringFieldUpdateOperationsInput | string
  order?: Prisma.IntFieldUpdateOperationsInput | number
  isEnabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type KitchenStageSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  restaurantId?: boolean
  status?: boolean
  displayName?: boolean
  color?: boolean
  order?: boolean
  isEnabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["kitchenStage"]>



export type KitchenStageSelectScalar = {
  id?: boolean
  restaurantId?: boolean
  status?: boolean
  displayName?: boolean
  color?: boolean
  order?: boolean
  isEnabled?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type KitchenStageOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "restaurantId" | "status" | "displayName" | "color" | "order" | "isEnabled" | "createdAt" | "updatedAt", ExtArgs["result"]["kitchenStage"]>
export type KitchenStageInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}

export type $KitchenStagePayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "KitchenStage"
  objects: {
    restaurant: Prisma.$RestaurantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    restaurantId: string
    status: string
    displayName: string
    color: string
    order: number
    isEnabled: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["kitchenStage"]>
  composites: {}
}

export type KitchenStageGetPayload<S extends boolean | null | undefined | KitchenStageDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload, S>

export type KitchenStageCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<KitchenStageFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: KitchenStageCountAggregateInputType | true
  }

export interface KitchenStageDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['KitchenStage'], meta: { name: 'KitchenStage' } }
  /**
   * Find zero or one KitchenStage that matches the filter.
   * @param {KitchenStageFindUniqueArgs} args - Arguments to find a KitchenStage
   * @example
   * // Get one KitchenStage
   * const kitchenStage = await prisma.kitchenStage.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends KitchenStageFindUniqueArgs>(args: Prisma.SelectSubset<T, KitchenStageFindUniqueArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one KitchenStage that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {KitchenStageFindUniqueOrThrowArgs} args - Arguments to find a KitchenStage
   * @example
   * // Get one KitchenStage
   * const kitchenStage = await prisma.kitchenStage.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends KitchenStageFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, KitchenStageFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KitchenStage that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageFindFirstArgs} args - Arguments to find a KitchenStage
   * @example
   * // Get one KitchenStage
   * const kitchenStage = await prisma.kitchenStage.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends KitchenStageFindFirstArgs>(args?: Prisma.SelectSubset<T, KitchenStageFindFirstArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first KitchenStage that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageFindFirstOrThrowArgs} args - Arguments to find a KitchenStage
   * @example
   * // Get one KitchenStage
   * const kitchenStage = await prisma.kitchenStage.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends KitchenStageFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, KitchenStageFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KitchenStages that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all KitchenStages
   * const kitchenStages = await prisma.kitchenStage.findMany()
   * 
   * // Get first 10 KitchenStages
   * const kitchenStages = await prisma.kitchenStage.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const kitchenStageWithIdOnly = await prisma.kitchenStage.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends KitchenStageFindManyArgs>(args?: Prisma.SelectSubset<T, KitchenStageFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a KitchenStage.
   * @param {KitchenStageCreateArgs} args - Arguments to create a KitchenStage.
   * @example
   * // Create one KitchenStage
   * const KitchenStage = await prisma.kitchenStage.create({
   *   data: {
   *     // ... data to create a KitchenStage
   *   }
   * })
   * 
   */
  create<T extends KitchenStageCreateArgs>(args: Prisma.SelectSubset<T, KitchenStageCreateArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many KitchenStages.
   * @param {KitchenStageCreateManyArgs} args - Arguments to create many KitchenStages.
   * @example
   * // Create many KitchenStages
   * const kitchenStage = await prisma.kitchenStage.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends KitchenStageCreateManyArgs>(args?: Prisma.SelectSubset<T, KitchenStageCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a KitchenStage.
   * @param {KitchenStageDeleteArgs} args - Arguments to delete one KitchenStage.
   * @example
   * // Delete one KitchenStage
   * const KitchenStage = await prisma.kitchenStage.delete({
   *   where: {
   *     // ... filter to delete one KitchenStage
   *   }
   * })
   * 
   */
  delete<T extends KitchenStageDeleteArgs>(args: Prisma.SelectSubset<T, KitchenStageDeleteArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one KitchenStage.
   * @param {KitchenStageUpdateArgs} args - Arguments to update one KitchenStage.
   * @example
   * // Update one KitchenStage
   * const kitchenStage = await prisma.kitchenStage.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends KitchenStageUpdateArgs>(args: Prisma.SelectSubset<T, KitchenStageUpdateArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more KitchenStages.
   * @param {KitchenStageDeleteManyArgs} args - Arguments to filter KitchenStages to delete.
   * @example
   * // Delete a few KitchenStages
   * const { count } = await prisma.kitchenStage.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends KitchenStageDeleteManyArgs>(args?: Prisma.SelectSubset<T, KitchenStageDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more KitchenStages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many KitchenStages
   * const kitchenStage = await prisma.kitchenStage.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends KitchenStageUpdateManyArgs>(args: Prisma.SelectSubset<T, KitchenStageUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one KitchenStage.
   * @param {KitchenStageUpsertArgs} args - Arguments to update or create a KitchenStage.
   * @example
   * // Update or create a KitchenStage
   * const kitchenStage = await prisma.kitchenStage.upsert({
   *   create: {
   *     // ... data to create a KitchenStage
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the KitchenStage we want to update
   *   }
   * })
   */
  upsert<T extends KitchenStageUpsertArgs>(args: Prisma.SelectSubset<T, KitchenStageUpsertArgs<ExtArgs>>): Prisma.Prisma__KitchenStageClient<runtime.Types.Result.GetResult<Prisma.$KitchenStagePayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more KitchenStages that matches the filter.
   * @param {KitchenStageFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const kitchenStage = await prisma.kitchenStage.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.KitchenStageFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a KitchenStage.
   * @param {KitchenStageAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const kitchenStage = await prisma.kitchenStage.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.KitchenStageAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of KitchenStages.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageCountArgs} args - Arguments to filter KitchenStages to count.
   * @example
   * // Count the number of KitchenStages
   * const count = await prisma.kitchenStage.count({
   *   where: {
   *     // ... the filter for the KitchenStages we want to count
   *   }
   * })
  **/
  count<T extends KitchenStageCountArgs>(
    args?: Prisma.Subset<T, KitchenStageCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], KitchenStageCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a KitchenStage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends KitchenStageAggregateArgs>(args: Prisma.Subset<T, KitchenStageAggregateArgs>): Prisma.PrismaPromise<GetKitchenStageAggregateType<T>>

  /**
   * Group by KitchenStage.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {KitchenStageGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends KitchenStageGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: KitchenStageGroupByArgs['orderBy'] }
      : { orderBy?: KitchenStageGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, KitchenStageGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetKitchenStageGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the KitchenStage model
 */
readonly fields: KitchenStageFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for KitchenStage.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__KitchenStageClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>): Prisma.Prisma__RestaurantClient<runtime.Types.Result.GetResult<Prisma.$RestaurantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the KitchenStage model
 */
export interface KitchenStageFieldRefs {
  readonly id: Prisma.FieldRef<"KitchenStage", 'String'>
  readonly restaurantId: Prisma.FieldRef<"KitchenStage", 'String'>
  readonly status: Prisma.FieldRef<"KitchenStage", 'String'>
  readonly displayName: Prisma.FieldRef<"KitchenStage", 'String'>
  readonly color: Prisma.FieldRef<"KitchenStage", 'String'>
  readonly order: Prisma.FieldRef<"KitchenStage", 'Int'>
  readonly isEnabled: Prisma.FieldRef<"KitchenStage", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"KitchenStage", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"KitchenStage", 'DateTime'>
}
    

// Custom InputTypes
/**
 * KitchenStage findUnique
 */
export type KitchenStageFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter, which KitchenStage to fetch.
   */
  where: Prisma.KitchenStageWhereUniqueInput
}

/**
 * KitchenStage findUniqueOrThrow
 */
export type KitchenStageFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter, which KitchenStage to fetch.
   */
  where: Prisma.KitchenStageWhereUniqueInput
}

/**
 * KitchenStage findFirst
 */
export type KitchenStageFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter, which KitchenStage to fetch.
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KitchenStages to fetch.
   */
  orderBy?: Prisma.KitchenStageOrderByWithRelationInput | Prisma.KitchenStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KitchenStages.
   */
  cursor?: Prisma.KitchenStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KitchenStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KitchenStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KitchenStages.
   */
  distinct?: Prisma.KitchenStageScalarFieldEnum | Prisma.KitchenStageScalarFieldEnum[]
}

/**
 * KitchenStage findFirstOrThrow
 */
export type KitchenStageFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter, which KitchenStage to fetch.
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KitchenStages to fetch.
   */
  orderBy?: Prisma.KitchenStageOrderByWithRelationInput | Prisma.KitchenStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for KitchenStages.
   */
  cursor?: Prisma.KitchenStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KitchenStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KitchenStages.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of KitchenStages.
   */
  distinct?: Prisma.KitchenStageScalarFieldEnum | Prisma.KitchenStageScalarFieldEnum[]
}

/**
 * KitchenStage findMany
 */
export type KitchenStageFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter, which KitchenStages to fetch.
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of KitchenStages to fetch.
   */
  orderBy?: Prisma.KitchenStageOrderByWithRelationInput | Prisma.KitchenStageOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing KitchenStages.
   */
  cursor?: Prisma.KitchenStageWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` KitchenStages from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` KitchenStages.
   */
  skip?: number
  distinct?: Prisma.KitchenStageScalarFieldEnum | Prisma.KitchenStageScalarFieldEnum[]
}

/**
 * KitchenStage create
 */
export type KitchenStageCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * The data needed to create a KitchenStage.
   */
  data: Prisma.XOR<Prisma.KitchenStageCreateInput, Prisma.KitchenStageUncheckedCreateInput>
}

/**
 * KitchenStage createMany
 */
export type KitchenStageCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many KitchenStages.
   */
  data: Prisma.KitchenStageCreateManyInput | Prisma.KitchenStageCreateManyInput[]
}

/**
 * KitchenStage update
 */
export type KitchenStageUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * The data needed to update a KitchenStage.
   */
  data: Prisma.XOR<Prisma.KitchenStageUpdateInput, Prisma.KitchenStageUncheckedUpdateInput>
  /**
   * Choose, which KitchenStage to update.
   */
  where: Prisma.KitchenStageWhereUniqueInput
}

/**
 * KitchenStage updateMany
 */
export type KitchenStageUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update KitchenStages.
   */
  data: Prisma.XOR<Prisma.KitchenStageUpdateManyMutationInput, Prisma.KitchenStageUncheckedUpdateManyInput>
  /**
   * Filter which KitchenStages to update
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * Limit how many KitchenStages to update.
   */
  limit?: number
}

/**
 * KitchenStage upsert
 */
export type KitchenStageUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * The filter to search for the KitchenStage to update in case it exists.
   */
  where: Prisma.KitchenStageWhereUniqueInput
  /**
   * In case the KitchenStage found by the `where` argument doesn't exist, create a new KitchenStage with this data.
   */
  create: Prisma.XOR<Prisma.KitchenStageCreateInput, Prisma.KitchenStageUncheckedCreateInput>
  /**
   * In case the KitchenStage was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.KitchenStageUpdateInput, Prisma.KitchenStageUncheckedUpdateInput>
}

/**
 * KitchenStage delete
 */
export type KitchenStageDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
  /**
   * Filter which KitchenStage to delete.
   */
  where: Prisma.KitchenStageWhereUniqueInput
}

/**
 * KitchenStage deleteMany
 */
export type KitchenStageDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which KitchenStages to delete
   */
  where?: Prisma.KitchenStageWhereInput
  /**
   * Limit how many KitchenStages to delete.
   */
  limit?: number
}

/**
 * KitchenStage findRaw
 */
export type KitchenStageFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * KitchenStage aggregateRaw
 */
export type KitchenStageAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * KitchenStage without action
 */
export type KitchenStageDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the KitchenStage
   */
  select?: Prisma.KitchenStageSelect<ExtArgs> | null
  /**
   * Omit specific fields from the KitchenStage
   */
  omit?: Prisma.KitchenStageOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.KitchenStageInclude<ExtArgs> | null
}
