
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `MenuRules` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model MenuRules
 * 
 */
export type MenuRulesModel = runtime.Types.Result.DefaultSelection<Prisma.$MenuRulesPayload>

export type AggregateMenuRules = {
  _count: MenuRulesCountAggregateOutputType | null
  _min: MenuRulesMinAggregateOutputType | null
  _max: MenuRulesMaxAggregateOutputType | null
}

export type MenuRulesMinAggregateOutputType = {
  id: string | null
  menuItemId: string | null
  restaurantId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MenuRulesMaxAggregateOutputType = {
  id: string | null
  menuItemId: string | null
  restaurantId: string | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type MenuRulesCountAggregateOutputType = {
  id: number
  menuItemId: number
  restaurantId: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type MenuRulesMinAggregateInputType = {
  id?: true
  menuItemId?: true
  restaurantId?: true
  createdAt?: true
  updatedAt?: true
}

export type MenuRulesMaxAggregateInputType = {
  id?: true
  menuItemId?: true
  restaurantId?: true
  createdAt?: true
  updatedAt?: true
}

export type MenuRulesCountAggregateInputType = {
  id?: true
  menuItemId?: true
  restaurantId?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type MenuRulesAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuRules to aggregate.
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuRules to fetch.
   */
  orderBy?: Prisma.MenuRulesOrderByWithRelationInput | Prisma.MenuRulesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.MenuRulesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned MenuRules
  **/
  _count?: true | MenuRulesCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: MenuRulesMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: MenuRulesMaxAggregateInputType
}

export type GetMenuRulesAggregateType<T extends MenuRulesAggregateArgs> = {
      [P in keyof T & keyof AggregateMenuRules]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateMenuRules[P]>
    : Prisma.GetScalarType<T[P], AggregateMenuRules[P]>
}




export type MenuRulesGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.MenuRulesWhereInput
  orderBy?: Prisma.MenuRulesOrderByWithAggregationInput | Prisma.MenuRulesOrderByWithAggregationInput[]
  by: Prisma.MenuRulesScalarFieldEnum[] | Prisma.MenuRulesScalarFieldEnum
  having?: Prisma.MenuRulesScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: MenuRulesCountAggregateInputType | true
  _min?: MenuRulesMinAggregateInputType
  _max?: MenuRulesMaxAggregateInputType
}

export type MenuRulesGroupByOutputType = {
  id: string
  menuItemId: string
  restaurantId: string
  createdAt: Date
  updatedAt: Date
  _count: MenuRulesCountAggregateOutputType | null
  _min: MenuRulesMinAggregateOutputType | null
  _max: MenuRulesMaxAggregateOutputType | null
}

type GetMenuRulesGroupByPayload<T extends MenuRulesGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<MenuRulesGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof MenuRulesGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], MenuRulesGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], MenuRulesGroupByOutputType[P]>
      }
    >
  >



export type MenuRulesWhereInput = {
  AND?: Prisma.MenuRulesWhereInput | Prisma.MenuRulesWhereInput[]
  OR?: Prisma.MenuRulesWhereInput[]
  NOT?: Prisma.MenuRulesWhereInput | Prisma.MenuRulesWhereInput[]
  id?: Prisma.StringFilter<"MenuRules"> | string
  menuItemId?: Prisma.StringFilter<"MenuRules"> | string
  restaurantId?: Prisma.StringFilter<"MenuRules"> | string
  appliedOptions?: Prisma.AppliedOptionCompositeListFilter | Prisma.AppliedOptionObjectEqualityInput[]
  createdAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
  menuItem?: Prisma.XOR<Prisma.MenuItemScalarRelationFilter, Prisma.MenuItemWhereInput>
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}

export type MenuRulesOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  menuItemId?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  appliedOptions?: Prisma.AppliedOptionOrderByCompositeAggregateInput
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  menuItem?: Prisma.MenuItemOrderByWithRelationInput
  restaurant?: Prisma.RestaurantOrderByWithRelationInput
}

export type MenuRulesWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  menuItemId?: string
  AND?: Prisma.MenuRulesWhereInput | Prisma.MenuRulesWhereInput[]
  OR?: Prisma.MenuRulesWhereInput[]
  NOT?: Prisma.MenuRulesWhereInput | Prisma.MenuRulesWhereInput[]
  restaurantId?: Prisma.StringFilter<"MenuRules"> | string
  appliedOptions?: Prisma.AppliedOptionCompositeListFilter | Prisma.AppliedOptionObjectEqualityInput[]
  createdAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
  menuItem?: Prisma.XOR<Prisma.MenuItemScalarRelationFilter, Prisma.MenuItemWhereInput>
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}, "id" | "menuItemId">

export type MenuRulesOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  menuItemId?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.MenuRulesCountOrderByAggregateInput
  _max?: Prisma.MenuRulesMaxOrderByAggregateInput
  _min?: Prisma.MenuRulesMinOrderByAggregateInput
}

export type MenuRulesScalarWhereWithAggregatesInput = {
  AND?: Prisma.MenuRulesScalarWhereWithAggregatesInput | Prisma.MenuRulesScalarWhereWithAggregatesInput[]
  OR?: Prisma.MenuRulesScalarWhereWithAggregatesInput[]
  NOT?: Prisma.MenuRulesScalarWhereWithAggregatesInput | Prisma.MenuRulesScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"MenuRules"> | string
  menuItemId?: Prisma.StringWithAggregatesFilter<"MenuRules"> | string
  restaurantId?: Prisma.StringWithAggregatesFilter<"MenuRules"> | string
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"MenuRules"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"MenuRules"> | Date | string
}

export type MenuRulesCreateInput = {
  id?: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
  menuItem: Prisma.MenuItemCreateNestedOneWithoutRulesInput
  restaurant: Prisma.RestaurantCreateNestedOneWithoutMenuRulesInput
}

export type MenuRulesUncheckedCreateInput = {
  id?: string
  menuItemId: string
  restaurantId: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuRulesUpdateInput = {
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menuItem?: Prisma.MenuItemUpdateOneRequiredWithoutRulesNestedInput
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutMenuRulesNestedInput
}

export type MenuRulesUncheckedUpdateInput = {
  menuItemId?: Prisma.StringFieldUpdateOperationsInput | string
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuRulesCreateManyInput = {
  id?: string
  menuItemId: string
  restaurantId: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuRulesUpdateManyMutationInput = {
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuRulesUncheckedUpdateManyInput = {
  menuItemId?: Prisma.StringFieldUpdateOperationsInput | string
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuRulesNullableScalarRelationFilter = {
  is?: Prisma.MenuRulesWhereInput | null
  isNot?: Prisma.MenuRulesWhereInput | null
}

export type AppliedOptionObjectEqualityInput = {
  optionId: string
  required: boolean
  order: number
  choiceAdjustments?: Prisma.ChoiceAdjustmentObjectEqualityInput[]
}

export type MenuRulesCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuItemId?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuRulesMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuItemId?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuRulesMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  menuItemId?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type MenuRulesListRelationFilter = {
  every?: Prisma.MenuRulesWhereInput
  some?: Prisma.MenuRulesWhereInput
  none?: Prisma.MenuRulesWhereInput
}

export type MenuRulesOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type MenuRulesCreateNestedOneWithoutMenuItemInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutMenuItemInput
  connect?: Prisma.MenuRulesWhereUniqueInput
}

export type MenuRulesUncheckedCreateNestedOneWithoutMenuItemInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutMenuItemInput
  connect?: Prisma.MenuRulesWhereUniqueInput
}

export type MenuRulesUpdateOneWithoutMenuItemNestedInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutMenuItemInput
  upsert?: Prisma.MenuRulesUpsertWithoutMenuItemInput
  disconnect?: Prisma.MenuRulesWhereInput | boolean
  delete?: Prisma.MenuRulesWhereInput | boolean
  connect?: Prisma.MenuRulesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MenuRulesUpdateToOneWithWhereWithoutMenuItemInput, Prisma.MenuRulesUpdateWithoutMenuItemInput>, Prisma.MenuRulesUncheckedUpdateWithoutMenuItemInput>
}

export type MenuRulesUncheckedUpdateOneWithoutMenuItemNestedInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutMenuItemInput
  upsert?: Prisma.MenuRulesUpsertWithoutMenuItemInput
  disconnect?: Prisma.MenuRulesWhereInput | boolean
  delete?: Prisma.MenuRulesWhereInput | boolean
  connect?: Prisma.MenuRulesWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.MenuRulesUpdateToOneWithWhereWithoutMenuItemInput, Prisma.MenuRulesUpdateWithoutMenuItemInput>, Prisma.MenuRulesUncheckedUpdateWithoutMenuItemInput>
}

export type AppliedOptionCreateInput = {
  optionId: string
  required?: boolean
  order?: number
  choiceAdjustments?: Prisma.ChoiceAdjustmentCreateInput | Prisma.ChoiceAdjustmentCreateInput[]
}

export type MenuRulesCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput> | Prisma.MenuRulesCreateWithoutRestaurantInput[] | Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput | Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.MenuRulesCreateManyRestaurantInputEnvelope
  connect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
}

export type MenuRulesUncheckedCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput> | Prisma.MenuRulesCreateWithoutRestaurantInput[] | Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput | Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.MenuRulesCreateManyRestaurantInputEnvelope
  connect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
}

export type MenuRulesUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput> | Prisma.MenuRulesCreateWithoutRestaurantInput[] | Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput | Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.MenuRulesUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.MenuRulesUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.MenuRulesCreateManyRestaurantInputEnvelope
  set?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  disconnect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  delete?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  connect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  update?: Prisma.MenuRulesUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.MenuRulesUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.MenuRulesUpdateManyWithWhereWithoutRestaurantInput | Prisma.MenuRulesUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.MenuRulesScalarWhereInput | Prisma.MenuRulesScalarWhereInput[]
}

export type MenuRulesUncheckedUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput> | Prisma.MenuRulesCreateWithoutRestaurantInput[] | Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput | Prisma.MenuRulesCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.MenuRulesUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.MenuRulesUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.MenuRulesCreateManyRestaurantInputEnvelope
  set?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  disconnect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  delete?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  connect?: Prisma.MenuRulesWhereUniqueInput | Prisma.MenuRulesWhereUniqueInput[]
  update?: Prisma.MenuRulesUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.MenuRulesUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.MenuRulesUpdateManyWithWhereWithoutRestaurantInput | Prisma.MenuRulesUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.MenuRulesScalarWhereInput | Prisma.MenuRulesScalarWhereInput[]
}

export type MenuRulesCreateWithoutMenuItemInput = {
  id?: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
  restaurant: Prisma.RestaurantCreateNestedOneWithoutMenuRulesInput
}

export type MenuRulesUncheckedCreateWithoutMenuItemInput = {
  id?: string
  restaurantId: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuRulesCreateOrConnectWithoutMenuItemInput = {
  where: Prisma.MenuRulesWhereUniqueInput
  create: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
}

export type MenuRulesUpsertWithoutMenuItemInput = {
  update: Prisma.XOR<Prisma.MenuRulesUpdateWithoutMenuItemInput, Prisma.MenuRulesUncheckedUpdateWithoutMenuItemInput>
  create: Prisma.XOR<Prisma.MenuRulesCreateWithoutMenuItemInput, Prisma.MenuRulesUncheckedCreateWithoutMenuItemInput>
  where?: Prisma.MenuRulesWhereInput
}

export type MenuRulesUpdateToOneWithWhereWithoutMenuItemInput = {
  where?: Prisma.MenuRulesWhereInput
  data: Prisma.XOR<Prisma.MenuRulesUpdateWithoutMenuItemInput, Prisma.MenuRulesUncheckedUpdateWithoutMenuItemInput>
}

export type MenuRulesUpdateWithoutMenuItemInput = {
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutMenuRulesNestedInput
}

export type MenuRulesUncheckedUpdateWithoutMenuItemInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuRulesCreateWithoutRestaurantInput = {
  id?: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
  menuItem: Prisma.MenuItemCreateNestedOneWithoutRulesInput
}

export type MenuRulesUncheckedCreateWithoutRestaurantInput = {
  id?: string
  menuItemId: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuRulesCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.MenuRulesWhereUniqueInput
  create: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput>
}

export type MenuRulesCreateManyRestaurantInputEnvelope = {
  data: Prisma.MenuRulesCreateManyRestaurantInput | Prisma.MenuRulesCreateManyRestaurantInput[]
}

export type MenuRulesUpsertWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.MenuRulesWhereUniqueInput
  update: Prisma.XOR<Prisma.MenuRulesUpdateWithoutRestaurantInput, Prisma.MenuRulesUncheckedUpdateWithoutRestaurantInput>
  create: Prisma.XOR<Prisma.MenuRulesCreateWithoutRestaurantInput, Prisma.MenuRulesUncheckedCreateWithoutRestaurantInput>
}

export type MenuRulesUpdateWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.MenuRulesWhereUniqueInput
  data: Prisma.XOR<Prisma.MenuRulesUpdateWithoutRestaurantInput, Prisma.MenuRulesUncheckedUpdateWithoutRestaurantInput>
}

export type MenuRulesUpdateManyWithWhereWithoutRestaurantInput = {
  where: Prisma.MenuRulesScalarWhereInput
  data: Prisma.XOR<Prisma.MenuRulesUpdateManyMutationInput, Prisma.MenuRulesUncheckedUpdateManyWithoutRestaurantInput>
}

export type MenuRulesScalarWhereInput = {
  AND?: Prisma.MenuRulesScalarWhereInput | Prisma.MenuRulesScalarWhereInput[]
  OR?: Prisma.MenuRulesScalarWhereInput[]
  NOT?: Prisma.MenuRulesScalarWhereInput | Prisma.MenuRulesScalarWhereInput[]
  id?: Prisma.StringFilter<"MenuRules"> | string
  menuItemId?: Prisma.StringFilter<"MenuRules"> | string
  restaurantId?: Prisma.StringFilter<"MenuRules"> | string
  createdAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"MenuRules"> | Date | string
}

export type MenuRulesCreateManyRestaurantInput = {
  id?: string
  menuItemId: string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListCreateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type MenuRulesUpdateWithoutRestaurantInput = {
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  menuItem?: Prisma.MenuItemUpdateOneRequiredWithoutRulesNestedInput
}

export type MenuRulesUncheckedUpdateWithoutRestaurantInput = {
  menuItemId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type MenuRulesUncheckedUpdateManyWithoutRestaurantInput = {
  menuItemId?: Prisma.StringFieldUpdateOperationsInput | string
  appliedOptions?: Prisma.XOR<Prisma.AppliedOptionListUpdateEnvelopeInput, Prisma.AppliedOptionCreateInput> | Prisma.AppliedOptionCreateInput[]
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type MenuRulesSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  menuItemId?: boolean
  restaurantId?: boolean
  appliedOptions?: boolean | Prisma.AppliedOptionDefaultArgs<ExtArgs>
  createdAt?: boolean
  updatedAt?: boolean
  menuItem?: boolean | Prisma.MenuItemDefaultArgs<ExtArgs>
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["menuRules"]>



export type MenuRulesSelectScalar = {
  id?: boolean
  menuItemId?: boolean
  restaurantId?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type MenuRulesOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "menuItemId" | "restaurantId" | "appliedOptions" | "createdAt" | "updatedAt", ExtArgs["result"]["menuRules"]>
export type MenuRulesInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  menuItem?: boolean | Prisma.MenuItemDefaultArgs<ExtArgs>
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}

export type $MenuRulesPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "MenuRules"
  objects: {
    menuItem: Prisma.$MenuItemPayload<ExtArgs>
    restaurant: Prisma.$RestaurantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    menuItemId: string
    restaurantId: string
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["menuRules"]>
  composites: {
    appliedOptions: Prisma.$AppliedOptionPayload[]
  }
}

export type MenuRulesGetPayload<S extends boolean | null | undefined | MenuRulesDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload, S>

export type MenuRulesCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<MenuRulesFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: MenuRulesCountAggregateInputType | true
  }

export interface MenuRulesDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['MenuRules'], meta: { name: 'MenuRules' } }
  /**
   * Find zero or one MenuRules that matches the filter.
   * @param {MenuRulesFindUniqueArgs} args - Arguments to find a MenuRules
   * @example
   * // Get one MenuRules
   * const menuRules = await prisma.menuRules.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends MenuRulesFindUniqueArgs>(args: Prisma.SelectSubset<T, MenuRulesFindUniqueArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one MenuRules that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {MenuRulesFindUniqueOrThrowArgs} args - Arguments to find a MenuRules
   * @example
   * // Get one MenuRules
   * const menuRules = await prisma.menuRules.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends MenuRulesFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, MenuRulesFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesFindFirstArgs} args - Arguments to find a MenuRules
   * @example
   * // Get one MenuRules
   * const menuRules = await prisma.menuRules.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends MenuRulesFindFirstArgs>(args?: Prisma.SelectSubset<T, MenuRulesFindFirstArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first MenuRules that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesFindFirstOrThrowArgs} args - Arguments to find a MenuRules
   * @example
   * // Get one MenuRules
   * const menuRules = await prisma.menuRules.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends MenuRulesFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, MenuRulesFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MenuRules that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all MenuRules
   * const menuRules = await prisma.menuRules.findMany()
   * 
   * // Get first 10 MenuRules
   * const menuRules = await prisma.menuRules.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const menuRulesWithIdOnly = await prisma.menuRules.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends MenuRulesFindManyArgs>(args?: Prisma.SelectSubset<T, MenuRulesFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a MenuRules.
   * @param {MenuRulesCreateArgs} args - Arguments to create a MenuRules.
   * @example
   * // Create one MenuRules
   * const MenuRules = await prisma.menuRules.create({
   *   data: {
   *     // ... data to create a MenuRules
   *   }
   * })
   * 
   */
  create<T extends MenuRulesCreateArgs>(args: Prisma.SelectSubset<T, MenuRulesCreateArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many MenuRules.
   * @param {MenuRulesCreateManyArgs} args - Arguments to create many MenuRules.
   * @example
   * // Create many MenuRules
   * const menuRules = await prisma.menuRules.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends MenuRulesCreateManyArgs>(args?: Prisma.SelectSubset<T, MenuRulesCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a MenuRules.
   * @param {MenuRulesDeleteArgs} args - Arguments to delete one MenuRules.
   * @example
   * // Delete one MenuRules
   * const MenuRules = await prisma.menuRules.delete({
   *   where: {
   *     // ... filter to delete one MenuRules
   *   }
   * })
   * 
   */
  delete<T extends MenuRulesDeleteArgs>(args: Prisma.SelectSubset<T, MenuRulesDeleteArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one MenuRules.
   * @param {MenuRulesUpdateArgs} args - Arguments to update one MenuRules.
   * @example
   * // Update one MenuRules
   * const menuRules = await prisma.menuRules.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends MenuRulesUpdateArgs>(args: Prisma.SelectSubset<T, MenuRulesUpdateArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more MenuRules.
   * @param {MenuRulesDeleteManyArgs} args - Arguments to filter MenuRules to delete.
   * @example
   * // Delete a few MenuRules
   * const { count } = await prisma.menuRules.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends MenuRulesDeleteManyArgs>(args?: Prisma.SelectSubset<T, MenuRulesDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more MenuRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many MenuRules
   * const menuRules = await prisma.menuRules.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends MenuRulesUpdateManyArgs>(args: Prisma.SelectSubset<T, MenuRulesUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one MenuRules.
   * @param {MenuRulesUpsertArgs} args - Arguments to update or create a MenuRules.
   * @example
   * // Update or create a MenuRules
   * const menuRules = await prisma.menuRules.upsert({
   *   create: {
   *     // ... data to create a MenuRules
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the MenuRules we want to update
   *   }
   * })
   */
  upsert<T extends MenuRulesUpsertArgs>(args: Prisma.SelectSubset<T, MenuRulesUpsertArgs<ExtArgs>>): Prisma.Prisma__MenuRulesClient<runtime.Types.Result.GetResult<Prisma.$MenuRulesPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more MenuRules that matches the filter.
   * @param {MenuRulesFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const menuRules = await prisma.menuRules.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.MenuRulesFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a MenuRules.
   * @param {MenuRulesAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const menuRules = await prisma.menuRules.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.MenuRulesAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of MenuRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesCountArgs} args - Arguments to filter MenuRules to count.
   * @example
   * // Count the number of MenuRules
   * const count = await prisma.menuRules.count({
   *   where: {
   *     // ... the filter for the MenuRules we want to count
   *   }
   * })
  **/
  count<T extends MenuRulesCountArgs>(
    args?: Prisma.Subset<T, MenuRulesCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], MenuRulesCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a MenuRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends MenuRulesAggregateArgs>(args: Prisma.Subset<T, MenuRulesAggregateArgs>): Prisma.PrismaPromise<GetMenuRulesAggregateType<T>>

  /**
   * Group by MenuRules.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {MenuRulesGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends MenuRulesGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: MenuRulesGroupByArgs['orderBy'] }
      : { orderBy?: MenuRulesGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, MenuRulesGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetMenuRulesGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the MenuRules model
 */
readonly fields: MenuRulesFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for MenuRules.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__MenuRulesClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  menuItem<T extends Prisma.MenuItemDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.MenuItemDefaultArgs<ExtArgs>>): Prisma.Prisma__MenuItemClient<runtime.Types.Result.GetResult<Prisma.$MenuItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>): Prisma.Prisma__RestaurantClient<runtime.Types.Result.GetResult<Prisma.$RestaurantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the MenuRules model
 */
export interface MenuRulesFieldRefs {
  readonly id: Prisma.FieldRef<"MenuRules", 'String'>
  readonly menuItemId: Prisma.FieldRef<"MenuRules", 'String'>
  readonly restaurantId: Prisma.FieldRef<"MenuRules", 'String'>
  readonly createdAt: Prisma.FieldRef<"MenuRules", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"MenuRules", 'DateTime'>
}
    

// Custom InputTypes
/**
 * MenuRules findUnique
 */
export type MenuRulesFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter, which MenuRules to fetch.
   */
  where: Prisma.MenuRulesWhereUniqueInput
}

/**
 * MenuRules findUniqueOrThrow
 */
export type MenuRulesFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter, which MenuRules to fetch.
   */
  where: Prisma.MenuRulesWhereUniqueInput
}

/**
 * MenuRules findFirst
 */
export type MenuRulesFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter, which MenuRules to fetch.
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuRules to fetch.
   */
  orderBy?: Prisma.MenuRulesOrderByWithRelationInput | Prisma.MenuRulesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuRules.
   */
  cursor?: Prisma.MenuRulesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuRules.
   */
  distinct?: Prisma.MenuRulesScalarFieldEnum | Prisma.MenuRulesScalarFieldEnum[]
}

/**
 * MenuRules findFirstOrThrow
 */
export type MenuRulesFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter, which MenuRules to fetch.
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuRules to fetch.
   */
  orderBy?: Prisma.MenuRulesOrderByWithRelationInput | Prisma.MenuRulesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for MenuRules.
   */
  cursor?: Prisma.MenuRulesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuRules.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of MenuRules.
   */
  distinct?: Prisma.MenuRulesScalarFieldEnum | Prisma.MenuRulesScalarFieldEnum[]
}

/**
 * MenuRules findMany
 */
export type MenuRulesFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter, which MenuRules to fetch.
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of MenuRules to fetch.
   */
  orderBy?: Prisma.MenuRulesOrderByWithRelationInput | Prisma.MenuRulesOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing MenuRules.
   */
  cursor?: Prisma.MenuRulesWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` MenuRules from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` MenuRules.
   */
  skip?: number
  distinct?: Prisma.MenuRulesScalarFieldEnum | Prisma.MenuRulesScalarFieldEnum[]
}

/**
 * MenuRules create
 */
export type MenuRulesCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * The data needed to create a MenuRules.
   */
  data: Prisma.XOR<Prisma.MenuRulesCreateInput, Prisma.MenuRulesUncheckedCreateInput>
}

/**
 * MenuRules createMany
 */
export type MenuRulesCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many MenuRules.
   */
  data: Prisma.MenuRulesCreateManyInput | Prisma.MenuRulesCreateManyInput[]
}

/**
 * MenuRules update
 */
export type MenuRulesUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * The data needed to update a MenuRules.
   */
  data: Prisma.XOR<Prisma.MenuRulesUpdateInput, Prisma.MenuRulesUncheckedUpdateInput>
  /**
   * Choose, which MenuRules to update.
   */
  where: Prisma.MenuRulesWhereUniqueInput
}

/**
 * MenuRules updateMany
 */
export type MenuRulesUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update MenuRules.
   */
  data: Prisma.XOR<Prisma.MenuRulesUpdateManyMutationInput, Prisma.MenuRulesUncheckedUpdateManyInput>
  /**
   * Filter which MenuRules to update
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * Limit how many MenuRules to update.
   */
  limit?: number
}

/**
 * MenuRules upsert
 */
export type MenuRulesUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * The filter to search for the MenuRules to update in case it exists.
   */
  where: Prisma.MenuRulesWhereUniqueInput
  /**
   * In case the MenuRules found by the `where` argument doesn't exist, create a new MenuRules with this data.
   */
  create: Prisma.XOR<Prisma.MenuRulesCreateInput, Prisma.MenuRulesUncheckedCreateInput>
  /**
   * In case the MenuRules was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.MenuRulesUpdateInput, Prisma.MenuRulesUncheckedUpdateInput>
}

/**
 * MenuRules delete
 */
export type MenuRulesDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
  /**
   * Filter which MenuRules to delete.
   */
  where: Prisma.MenuRulesWhereUniqueInput
}

/**
 * MenuRules deleteMany
 */
export type MenuRulesDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which MenuRules to delete
   */
  where?: Prisma.MenuRulesWhereInput
  /**
   * Limit how many MenuRules to delete.
   */
  limit?: number
}

/**
 * MenuRules findRaw
 */
export type MenuRulesFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * MenuRules aggregateRaw
 */
export type MenuRulesAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * MenuRules without action
 */
export type MenuRulesDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the MenuRules
   */
  select?: Prisma.MenuRulesSelect<ExtArgs> | null
  /**
   * Omit specific fields from the MenuRules
   */
  omit?: Prisma.MenuRulesOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.MenuRulesInclude<ExtArgs> | null
}
