
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Nutrition` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Nutrition
 * 
 */
export type NutritionModel = runtime.Types.Result.DefaultSelection<Prisma.$NutritionPayload>






export type NutritionNullableCompositeFilter = {
  equals?: Prisma.NutritionObjectEqualityInput | null
  is?: Prisma.NutritionWhereInput | null
  isNot?: Prisma.NutritionWhereInput | null
  isSet?: boolean
}

export type NutritionOrderByInput = {
  calories?: Prisma.SortOrder
  fat?: Prisma.SortOrder
  protein?: Prisma.SortOrder
  carbs?: Prisma.SortOrder
}

export type NutritionNullableCreateEnvelopeInput = {
  set?: Prisma.NutritionCreateInput | null
}

export type NutritionNullableUpdateEnvelopeInput = {
  set?: Prisma.NutritionCreateInput | null
  upsert?: Prisma.NutritionUpsertInput
  unset?: boolean
}

export type NutritionWhereInput = {
  AND?: Prisma.NutritionWhereInput | Prisma.NutritionWhereInput[]
  OR?: Prisma.NutritionWhereInput[]
  NOT?: Prisma.NutritionWhereInput | Prisma.NutritionWhereInput[]
  calories?: Prisma.IntFilter<"Nutrition"> | number
  fat?: Prisma.FloatFilter<"Nutrition"> | number
  protein?: Prisma.FloatFilter<"Nutrition"> | number
  carbs?: Prisma.FloatFilter<"Nutrition"> | number
}

export type NutritionUpsertInput = {
  set: Prisma.NutritionCreateInput | null
  update: Prisma.NutritionUpdateInput
}

export type NutritionUpdateInput = {
  calories?: Prisma.IntFieldUpdateOperationsInput | number
  fat?: Prisma.FloatFieldUpdateOperationsInput | number
  protein?: Prisma.FloatFieldUpdateOperationsInput | number
  carbs?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type NutritionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  calories?: boolean
  fat?: boolean
  protein?: boolean
  carbs?: boolean
}, ExtArgs["result"]["nutrition"]>



export type NutritionSelectScalar = {
  calories?: boolean
  fat?: boolean
  protein?: boolean
  carbs?: boolean
}

export type NutritionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"calories" | "fat" | "protein" | "carbs", ExtArgs["result"]["nutrition"]>

export type $NutritionPayload = {
  name: "Nutrition"
  objects: {}
  scalars: {
    calories: number
    fat: number
    protein: number
    carbs: number
  }
  composites: {}
}

export type NutritionGetPayload<S extends boolean | null | undefined | NutritionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$NutritionPayload, S>





/**
 * Fields of the Nutrition model
 */
export interface NutritionFieldRefs {
  readonly calories: Prisma.FieldRef<"Nutrition", 'Int'>
  readonly fat: Prisma.FieldRef<"Nutrition", 'Float'>
  readonly protein: Prisma.FieldRef<"Nutrition", 'Float'>
  readonly carbs: Prisma.FieldRef<"Nutrition", 'Float'>
}
    

// Custom InputTypes
/**
 * Nutrition without action
 */
export type NutritionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Nutrition
   */
  select?: Prisma.NutritionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Nutrition
   */
  omit?: Prisma.NutritionOmit<ExtArgs> | null
}
