
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `Order` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Order
 * 
 */
export type OrderModel = runtime.Types.Result.DefaultSelection<Prisma.$OrderPayload>

export type AggregateOrder = {
  _count: OrderCountAggregateOutputType | null
  _avg: OrderAvgAggregateOutputType | null
  _sum: OrderSumAggregateOutputType | null
  _min: OrderMinAggregateOutputType | null
  _max: OrderMaxAggregateOutputType | null
}

export type OrderAvgAggregateOutputType = {
  priority: number | null
  subtotal: number | null
  tax: number | null
  tip: number | null
  deliveryFee: number | null
  platformFee: number | null
  total: number | null
  deliveryDistance: number | null
}

export type OrderSumAggregateOutputType = {
  priority: number | null
  subtotal: number | null
  tax: number | null
  tip: number | null
  deliveryFee: number | null
  platformFee: number | null
  total: number | null
  deliveryDistance: number | null
}

export type OrderMinAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  orderNumber: string | null
  customerId: string | null
  customerName: string | null
  customerEmail: string | null
  customerPhone: string | null
  orderType: string | null
  status: string | null
  priority: number | null
  paymentStatus: string | null
  paymentMethod: string | null
  paymentIntentId: string | null
  paymentClientSecret: string | null
  chargeId: string | null
  subtotal: number | null
  tax: number | null
  tip: number | null
  deliveryFee: number | null
  platformFee: number | null
  total: number | null
  deliveryDistance: number | null
  specialInstructions: string | null
  timezone: string | null
  localDate: string | null
  localDateTime: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrderMaxAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  orderNumber: string | null
  customerId: string | null
  customerName: string | null
  customerEmail: string | null
  customerPhone: string | null
  orderType: string | null
  status: string | null
  priority: number | null
  paymentStatus: string | null
  paymentMethod: string | null
  paymentIntentId: string | null
  paymentClientSecret: string | null
  chargeId: string | null
  subtotal: number | null
  tax: number | null
  tip: number | null
  deliveryFee: number | null
  platformFee: number | null
  total: number | null
  deliveryDistance: number | null
  specialInstructions: string | null
  timezone: string | null
  localDate: string | null
  localDateTime: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type OrderCountAggregateOutputType = {
  id: number
  restaurantId: number
  orderNumber: number
  customerId: number
  customerName: number
  customerEmail: number
  customerPhone: number
  customerAddress: number
  restaurantInfo: number
  orderType: number
  status: number
  priority: number
  paymentStatus: number
  paymentMethod: number
  paymentIntentId: number
  paymentClientSecret: number
  chargeId: number
  subtotal: number
  tax: number
  taxBreakdown: number
  tip: number
  deliveryFee: number
  platformFee: number
  total: number
  deliveryDistance: number
  deliveryInfo: number
  specialInstructions: number
  timezone: number
  localDate: number
  localDateTime: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type OrderAvgAggregateInputType = {
  priority?: true
  subtotal?: true
  tax?: true
  tip?: true
  deliveryFee?: true
  platformFee?: true
  total?: true
  deliveryDistance?: true
}

export type OrderSumAggregateInputType = {
  priority?: true
  subtotal?: true
  tax?: true
  tip?: true
  deliveryFee?: true
  platformFee?: true
  total?: true
  deliveryDistance?: true
}

export type OrderMinAggregateInputType = {
  id?: true
  restaurantId?: true
  orderNumber?: true
  customerId?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  orderType?: true
  status?: true
  priority?: true
  paymentStatus?: true
  paymentMethod?: true
  paymentIntentId?: true
  paymentClientSecret?: true
  chargeId?: true
  subtotal?: true
  tax?: true
  tip?: true
  deliveryFee?: true
  platformFee?: true
  total?: true
  deliveryDistance?: true
  specialInstructions?: true
  timezone?: true
  localDate?: true
  localDateTime?: true
  createdAt?: true
  updatedAt?: true
}

export type OrderMaxAggregateInputType = {
  id?: true
  restaurantId?: true
  orderNumber?: true
  customerId?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  orderType?: true
  status?: true
  priority?: true
  paymentStatus?: true
  paymentMethod?: true
  paymentIntentId?: true
  paymentClientSecret?: true
  chargeId?: true
  subtotal?: true
  tax?: true
  tip?: true
  deliveryFee?: true
  platformFee?: true
  total?: true
  deliveryDistance?: true
  specialInstructions?: true
  timezone?: true
  localDate?: true
  localDateTime?: true
  createdAt?: true
  updatedAt?: true
}

export type OrderCountAggregateInputType = {
  id?: true
  restaurantId?: true
  orderNumber?: true
  customerId?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  customerAddress?: true
  restaurantInfo?: true
  orderType?: true
  status?: true
  priority?: true
  paymentStatus?: true
  paymentMethod?: true
  paymentIntentId?: true
  paymentClientSecret?: true
  chargeId?: true
  subtotal?: true
  tax?: true
  taxBreakdown?: true
  tip?: true
  deliveryFee?: true
  platformFee?: true
  total?: true
  deliveryDistance?: true
  deliveryInfo?: true
  specialInstructions?: true
  timezone?: true
  localDate?: true
  localDateTime?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type OrderAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Order to aggregate.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Orders
  **/
  _count?: true | OrderCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: OrderAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: OrderSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: OrderMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: OrderMaxAggregateInputType
}

export type GetOrderAggregateType<T extends OrderAggregateArgs> = {
      [P in keyof T & keyof AggregateOrder]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateOrder[P]>
    : Prisma.GetScalarType<T[P], AggregateOrder[P]>
}




export type OrderGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.OrderWhereInput
  orderBy?: Prisma.OrderOrderByWithAggregationInput | Prisma.OrderOrderByWithAggregationInput[]
  by: Prisma.OrderScalarFieldEnum[] | Prisma.OrderScalarFieldEnum
  having?: Prisma.OrderScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: OrderCountAggregateInputType | true
  _avg?: OrderAvgAggregateInputType
  _sum?: OrderSumAggregateInputType
  _min?: OrderMinAggregateInputType
  _max?: OrderMaxAggregateInputType
}

export type OrderGroupByOutputType = {
  id: string
  restaurantId: string
  orderNumber: string
  customerId: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress: runtime.JsonValue | null
  restaurantInfo: runtime.JsonValue
  orderType: string
  status: string
  priority: number
  paymentStatus: string
  paymentMethod: string
  paymentIntentId: string | null
  paymentClientSecret: string | null
  chargeId: string | null
  subtotal: number
  tax: number
  taxBreakdown: runtime.JsonValue | null
  tip: number
  deliveryFee: number
  platformFee: number
  total: number
  deliveryDistance: number | null
  deliveryInfo: runtime.JsonValue | null
  specialInstructions: string | null
  timezone: string
  localDate: string | null
  localDateTime: Date | null
  createdAt: Date
  updatedAt: Date
  _count: OrderCountAggregateOutputType | null
  _avg: OrderAvgAggregateOutputType | null
  _sum: OrderSumAggregateOutputType | null
  _min: OrderMinAggregateOutputType | null
  _max: OrderMaxAggregateOutputType | null
}

type GetOrderGroupByPayload<T extends OrderGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<OrderGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof OrderGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], OrderGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], OrderGroupByOutputType[P]>
      }
    >
  >



export type OrderWhereInput = {
  AND?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  OR?: Prisma.OrderWhereInput[]
  NOT?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  id?: Prisma.StringFilter<"Order"> | string
  restaurantId?: Prisma.StringFilter<"Order"> | string
  orderNumber?: Prisma.StringFilter<"Order"> | string
  customerId?: Prisma.StringNullableFilter<"Order"> | string | null
  customerName?: Prisma.StringFilter<"Order"> | string
  customerEmail?: Prisma.StringFilter<"Order"> | string
  customerPhone?: Prisma.StringFilter<"Order"> | string
  customerAddress?: Prisma.JsonNullableFilter<"Order">
  restaurantInfo?: Prisma.JsonFilter<"Order">
  items?: Prisma.OrderItemCompositeListFilter | Prisma.OrderItemObjectEqualityInput[]
  orderType?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  priority?: Prisma.IntFilter<"Order"> | number
  paymentStatus?: Prisma.StringFilter<"Order"> | string
  paymentMethod?: Prisma.StringFilter<"Order"> | string
  paymentIntentId?: Prisma.StringNullableFilter<"Order"> | string | null
  paymentClientSecret?: Prisma.StringNullableFilter<"Order"> | string | null
  chargeId?: Prisma.StringNullableFilter<"Order"> | string | null
  subtotal?: Prisma.FloatFilter<"Order"> | number
  tax?: Prisma.FloatFilter<"Order"> | number
  taxBreakdown?: Prisma.JsonNullableFilter<"Order">
  tip?: Prisma.FloatFilter<"Order"> | number
  deliveryFee?: Prisma.FloatFilter<"Order"> | number
  platformFee?: Prisma.FloatFilter<"Order"> | number
  total?: Prisma.FloatFilter<"Order"> | number
  deliveryDistance?: Prisma.FloatNullableFilter<"Order"> | number | null
  deliveryInfo?: Prisma.JsonNullableFilter<"Order">
  specialInstructions?: Prisma.StringNullableFilter<"Order"> | string | null
  timezone?: Prisma.StringFilter<"Order"> | string
  localDate?: Prisma.StringNullableFilter<"Order"> | string | null
  localDateTime?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Order"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Order"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}

export type OrderOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  customerAddress?: Prisma.SortOrder
  restaurantInfo?: Prisma.SortOrder
  items?: Prisma.OrderItemOrderByCompositeAggregateInput
  orderType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  paymentIntentId?: Prisma.SortOrder
  paymentClientSecret?: Prisma.SortOrder
  chargeId?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  taxBreakdown?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
  deliveryInfo?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  localDate?: Prisma.SortOrder
  localDateTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  restaurant?: Prisma.RestaurantOrderByWithRelationInput
}

export type OrderWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  orderNumber?: string
  AND?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  OR?: Prisma.OrderWhereInput[]
  NOT?: Prisma.OrderWhereInput | Prisma.OrderWhereInput[]
  restaurantId?: Prisma.StringFilter<"Order"> | string
  customerId?: Prisma.StringNullableFilter<"Order"> | string | null
  customerName?: Prisma.StringFilter<"Order"> | string
  customerEmail?: Prisma.StringFilter<"Order"> | string
  customerPhone?: Prisma.StringFilter<"Order"> | string
  customerAddress?: Prisma.JsonNullableFilter<"Order">
  restaurantInfo?: Prisma.JsonFilter<"Order">
  items?: Prisma.OrderItemCompositeListFilter | Prisma.OrderItemObjectEqualityInput[]
  orderType?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  priority?: Prisma.IntFilter<"Order"> | number
  paymentStatus?: Prisma.StringFilter<"Order"> | string
  paymentMethod?: Prisma.StringFilter<"Order"> | string
  paymentIntentId?: Prisma.StringNullableFilter<"Order"> | string | null
  paymentClientSecret?: Prisma.StringNullableFilter<"Order"> | string | null
  chargeId?: Prisma.StringNullableFilter<"Order"> | string | null
  subtotal?: Prisma.FloatFilter<"Order"> | number
  tax?: Prisma.FloatFilter<"Order"> | number
  taxBreakdown?: Prisma.JsonNullableFilter<"Order">
  tip?: Prisma.FloatFilter<"Order"> | number
  deliveryFee?: Prisma.FloatFilter<"Order"> | number
  platformFee?: Prisma.FloatFilter<"Order"> | number
  total?: Prisma.FloatFilter<"Order"> | number
  deliveryDistance?: Prisma.FloatNullableFilter<"Order"> | number | null
  deliveryInfo?: Prisma.JsonNullableFilter<"Order">
  specialInstructions?: Prisma.StringNullableFilter<"Order"> | string | null
  timezone?: Prisma.StringFilter<"Order"> | string
  localDate?: Prisma.StringNullableFilter<"Order"> | string | null
  localDateTime?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Order"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Order"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}, "id" | "orderNumber">

export type OrderOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  customerAddress?: Prisma.SortOrder
  restaurantInfo?: Prisma.SortOrder
  orderType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  paymentIntentId?: Prisma.SortOrder
  paymentClientSecret?: Prisma.SortOrder
  chargeId?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  taxBreakdown?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
  deliveryInfo?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  localDate?: Prisma.SortOrder
  localDateTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.OrderCountOrderByAggregateInput
  _avg?: Prisma.OrderAvgOrderByAggregateInput
  _max?: Prisma.OrderMaxOrderByAggregateInput
  _min?: Prisma.OrderMinOrderByAggregateInput
  _sum?: Prisma.OrderSumOrderByAggregateInput
}

export type OrderScalarWhereWithAggregatesInput = {
  AND?: Prisma.OrderScalarWhereWithAggregatesInput | Prisma.OrderScalarWhereWithAggregatesInput[]
  OR?: Prisma.OrderScalarWhereWithAggregatesInput[]
  NOT?: Prisma.OrderScalarWhereWithAggregatesInput | Prisma.OrderScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Order"> | string
  restaurantId?: Prisma.StringWithAggregatesFilter<"Order"> | string
  orderNumber?: Prisma.StringWithAggregatesFilter<"Order"> | string
  customerId?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  customerName?: Prisma.StringWithAggregatesFilter<"Order"> | string
  customerEmail?: Prisma.StringWithAggregatesFilter<"Order"> | string
  customerPhone?: Prisma.StringWithAggregatesFilter<"Order"> | string
  customerAddress?: Prisma.JsonNullableWithAggregatesFilter<"Order">
  restaurantInfo?: Prisma.JsonWithAggregatesFilter<"Order">
  orderType?: Prisma.StringWithAggregatesFilter<"Order"> | string
  status?: Prisma.StringWithAggregatesFilter<"Order"> | string
  priority?: Prisma.IntWithAggregatesFilter<"Order"> | number
  paymentStatus?: Prisma.StringWithAggregatesFilter<"Order"> | string
  paymentMethod?: Prisma.StringWithAggregatesFilter<"Order"> | string
  paymentIntentId?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  paymentClientSecret?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  chargeId?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  subtotal?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  tax?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  taxBreakdown?: Prisma.JsonNullableWithAggregatesFilter<"Order">
  tip?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  deliveryFee?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  platformFee?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  total?: Prisma.FloatWithAggregatesFilter<"Order"> | number
  deliveryDistance?: Prisma.FloatNullableWithAggregatesFilter<"Order"> | number | null
  deliveryInfo?: Prisma.JsonNullableWithAggregatesFilter<"Order">
  specialInstructions?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  timezone?: Prisma.StringWithAggregatesFilter<"Order"> | string
  localDate?: Prisma.StringNullableWithAggregatesFilter<"Order"> | string | null
  localDateTime?: Prisma.DateTimeNullableWithAggregatesFilter<"Order"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Order"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Order"> | Date | string
}

export type OrderCreateInput = {
  id?: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  restaurant: Prisma.RestaurantCreateNestedOneWithoutOrdersInput
}

export type OrderUncheckedCreateInput = {
  id?: string
  restaurantId: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrderUpdateInput = {
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutOrdersNestedInput
}

export type OrderUncheckedUpdateInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderCreateManyInput = {
  id?: string
  restaurantId: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrderUpdateManyMutationInput = {
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderUncheckedUpdateManyInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderItemObjectEqualityInput = {
  menuItemId: string
  name: string
  price: number
  quantity: number
  options?: Prisma.SelectedOptionObjectEqualityInput[]
  specialInstructions?: string | null
}

export type OrderCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  customerAddress?: Prisma.SortOrder
  restaurantInfo?: Prisma.SortOrder
  orderType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  paymentIntentId?: Prisma.SortOrder
  paymentClientSecret?: Prisma.SortOrder
  chargeId?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  taxBreakdown?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
  deliveryInfo?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  localDate?: Prisma.SortOrder
  localDateTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrderAvgOrderByAggregateInput = {
  priority?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
}

export type OrderMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  orderType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  paymentIntentId?: Prisma.SortOrder
  paymentClientSecret?: Prisma.SortOrder
  chargeId?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  localDate?: Prisma.SortOrder
  localDateTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrderMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  orderNumber?: Prisma.SortOrder
  customerId?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  orderType?: Prisma.SortOrder
  status?: Prisma.SortOrder
  priority?: Prisma.SortOrder
  paymentStatus?: Prisma.SortOrder
  paymentMethod?: Prisma.SortOrder
  paymentIntentId?: Prisma.SortOrder
  paymentClientSecret?: Prisma.SortOrder
  chargeId?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
  specialInstructions?: Prisma.SortOrder
  timezone?: Prisma.SortOrder
  localDate?: Prisma.SortOrder
  localDateTime?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type OrderSumOrderByAggregateInput = {
  priority?: Prisma.SortOrder
  subtotal?: Prisma.SortOrder
  tax?: Prisma.SortOrder
  tip?: Prisma.SortOrder
  deliveryFee?: Prisma.SortOrder
  platformFee?: Prisma.SortOrder
  total?: Prisma.SortOrder
  deliveryDistance?: Prisma.SortOrder
}

export type OrderListRelationFilter = {
  every?: Prisma.OrderWhereInput
  some?: Prisma.OrderWhereInput
  none?: Prisma.OrderWhereInput
}

export type OrderOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type OrderItemCreateInput = {
  menuItemId: string
  name: string
  price: number
  quantity: number
  options?: Prisma.SelectedOptionCreateInput | Prisma.SelectedOptionCreateInput[]
  specialInstructions?: string | null
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
  unset?: boolean
}

export type OrderCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput> | Prisma.OrderCreateWithoutRestaurantInput[] | Prisma.OrderUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutRestaurantInput | Prisma.OrderCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.OrderCreateManyRestaurantInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUncheckedCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput> | Prisma.OrderCreateWithoutRestaurantInput[] | Prisma.OrderUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutRestaurantInput | Prisma.OrderCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.OrderCreateManyRestaurantInputEnvelope
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
}

export type OrderUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput> | Prisma.OrderCreateWithoutRestaurantInput[] | Prisma.OrderUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutRestaurantInput | Prisma.OrderCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.OrderUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.OrderCreateManyRestaurantInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.OrderUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutRestaurantInput | Prisma.OrderUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderUncheckedUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput> | Prisma.OrderCreateWithoutRestaurantInput[] | Prisma.OrderUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.OrderCreateOrConnectWithoutRestaurantInput | Prisma.OrderCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.OrderUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.OrderUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.OrderCreateManyRestaurantInputEnvelope
  set?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  disconnect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  delete?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  connect?: Prisma.OrderWhereUniqueInput | Prisma.OrderWhereUniqueInput[]
  update?: Prisma.OrderUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.OrderUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.OrderUpdateManyWithWhereWithoutRestaurantInput | Prisma.OrderUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
}

export type OrderCreateWithoutRestaurantInput = {
  id?: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrderUncheckedCreateWithoutRestaurantInput = {
  id?: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrderCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.OrderWhereUniqueInput
  create: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput>
}

export type OrderCreateManyRestaurantInputEnvelope = {
  data: Prisma.OrderCreateManyRestaurantInput | Prisma.OrderCreateManyRestaurantInput[]
}

export type OrderUpsertWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.OrderWhereUniqueInput
  update: Prisma.XOR<Prisma.OrderUpdateWithoutRestaurantInput, Prisma.OrderUncheckedUpdateWithoutRestaurantInput>
  create: Prisma.XOR<Prisma.OrderCreateWithoutRestaurantInput, Prisma.OrderUncheckedCreateWithoutRestaurantInput>
}

export type OrderUpdateWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.OrderWhereUniqueInput
  data: Prisma.XOR<Prisma.OrderUpdateWithoutRestaurantInput, Prisma.OrderUncheckedUpdateWithoutRestaurantInput>
}

export type OrderUpdateManyWithWhereWithoutRestaurantInput = {
  where: Prisma.OrderScalarWhereInput
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyWithoutRestaurantInput>
}

export type OrderScalarWhereInput = {
  AND?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
  OR?: Prisma.OrderScalarWhereInput[]
  NOT?: Prisma.OrderScalarWhereInput | Prisma.OrderScalarWhereInput[]
  id?: Prisma.StringFilter<"Order"> | string
  restaurantId?: Prisma.StringFilter<"Order"> | string
  orderNumber?: Prisma.StringFilter<"Order"> | string
  customerId?: Prisma.StringNullableFilter<"Order"> | string | null
  customerName?: Prisma.StringFilter<"Order"> | string
  customerEmail?: Prisma.StringFilter<"Order"> | string
  customerPhone?: Prisma.StringFilter<"Order"> | string
  customerAddress?: Prisma.JsonNullableFilter<"Order">
  restaurantInfo?: Prisma.JsonFilter<"Order">
  orderType?: Prisma.StringFilter<"Order"> | string
  status?: Prisma.StringFilter<"Order"> | string
  priority?: Prisma.IntFilter<"Order"> | number
  paymentStatus?: Prisma.StringFilter<"Order"> | string
  paymentMethod?: Prisma.StringFilter<"Order"> | string
  paymentIntentId?: Prisma.StringNullableFilter<"Order"> | string | null
  paymentClientSecret?: Prisma.StringNullableFilter<"Order"> | string | null
  chargeId?: Prisma.StringNullableFilter<"Order"> | string | null
  subtotal?: Prisma.FloatFilter<"Order"> | number
  tax?: Prisma.FloatFilter<"Order"> | number
  taxBreakdown?: Prisma.JsonNullableFilter<"Order">
  tip?: Prisma.FloatFilter<"Order"> | number
  deliveryFee?: Prisma.FloatFilter<"Order"> | number
  platformFee?: Prisma.FloatFilter<"Order"> | number
  total?: Prisma.FloatFilter<"Order"> | number
  deliveryDistance?: Prisma.FloatNullableFilter<"Order"> | number | null
  deliveryInfo?: Prisma.JsonNullableFilter<"Order">
  specialInstructions?: Prisma.StringNullableFilter<"Order"> | string | null
  timezone?: Prisma.StringFilter<"Order"> | string
  localDate?: Prisma.StringNullableFilter<"Order"> | string | null
  localDateTime?: Prisma.DateTimeNullableFilter<"Order"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Order"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Order"> | Date | string
}

export type OrderCreateManyRestaurantInput = {
  id?: string
  orderNumber: string
  customerId?: string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  customerAddress?: runtime.InputJsonValue | null
  restaurantInfo: runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListCreateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType: string
  status?: string
  priority?: number
  paymentStatus?: string
  paymentMethod: string
  paymentIntentId?: string | null
  paymentClientSecret?: string | null
  chargeId?: string | null
  subtotal: number
  tax: number
  taxBreakdown?: runtime.InputJsonValue | null
  tip?: number
  deliveryFee?: number
  platformFee?: number
  total: number
  deliveryDistance?: number | null
  deliveryInfo?: runtime.InputJsonValue | null
  specialInstructions?: string | null
  timezone?: string
  localDate?: string | null
  localDateTime?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type OrderUpdateWithoutRestaurantInput = {
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderUncheckedUpdateWithoutRestaurantInput = {
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type OrderUncheckedUpdateManyWithoutRestaurantInput = {
  orderNumber?: Prisma.StringFieldUpdateOperationsInput | string
  customerId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  customerAddress?: runtime.InputJsonValue | runtime.InputJsonValue | null
  restaurantInfo?: runtime.InputJsonValue | runtime.InputJsonValue
  items?: Prisma.XOR<Prisma.OrderItemListUpdateEnvelopeInput, Prisma.OrderItemCreateInput> | Prisma.OrderItemCreateInput[]
  orderType?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.StringFieldUpdateOperationsInput | string
  priority?: Prisma.IntFieldUpdateOperationsInput | number
  paymentStatus?: Prisma.StringFieldUpdateOperationsInput | string
  paymentMethod?: Prisma.StringFieldUpdateOperationsInput | string
  paymentIntentId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  paymentClientSecret?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  chargeId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  subtotal?: Prisma.FloatFieldUpdateOperationsInput | number
  tax?: Prisma.FloatFieldUpdateOperationsInput | number
  taxBreakdown?: runtime.InputJsonValue | runtime.InputJsonValue | null
  tip?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryFee?: Prisma.FloatFieldUpdateOperationsInput | number
  platformFee?: Prisma.FloatFieldUpdateOperationsInput | number
  total?: Prisma.FloatFieldUpdateOperationsInput | number
  deliveryDistance?: Prisma.NullableFloatFieldUpdateOperationsInput | number | null
  deliveryInfo?: runtime.InputJsonValue | runtime.InputJsonValue | null
  specialInstructions?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  timezone?: Prisma.StringFieldUpdateOperationsInput | string
  localDate?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  localDateTime?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type OrderSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  restaurantId?: boolean
  orderNumber?: boolean
  customerId?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  customerAddress?: boolean
  restaurantInfo?: boolean
  items?: boolean | Prisma.OrderItemDefaultArgs<ExtArgs>
  orderType?: boolean
  status?: boolean
  priority?: boolean
  paymentStatus?: boolean
  paymentMethod?: boolean
  paymentIntentId?: boolean
  paymentClientSecret?: boolean
  chargeId?: boolean
  subtotal?: boolean
  tax?: boolean
  taxBreakdown?: boolean
  tip?: boolean
  deliveryFee?: boolean
  platformFee?: boolean
  total?: boolean
  deliveryDistance?: boolean
  deliveryInfo?: boolean
  specialInstructions?: boolean
  timezone?: boolean
  localDate?: boolean
  localDateTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["order"]>



export type OrderSelectScalar = {
  id?: boolean
  restaurantId?: boolean
  orderNumber?: boolean
  customerId?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  customerAddress?: boolean
  restaurantInfo?: boolean
  orderType?: boolean
  status?: boolean
  priority?: boolean
  paymentStatus?: boolean
  paymentMethod?: boolean
  paymentIntentId?: boolean
  paymentClientSecret?: boolean
  chargeId?: boolean
  subtotal?: boolean
  tax?: boolean
  taxBreakdown?: boolean
  tip?: boolean
  deliveryFee?: boolean
  platformFee?: boolean
  total?: boolean
  deliveryDistance?: boolean
  deliveryInfo?: boolean
  specialInstructions?: boolean
  timezone?: boolean
  localDate?: boolean
  localDateTime?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type OrderOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "restaurantId" | "orderNumber" | "customerId" | "customerName" | "customerEmail" | "customerPhone" | "customerAddress" | "restaurantInfo" | "items" | "orderType" | "status" | "priority" | "paymentStatus" | "paymentMethod" | "paymentIntentId" | "paymentClientSecret" | "chargeId" | "subtotal" | "tax" | "taxBreakdown" | "tip" | "deliveryFee" | "platformFee" | "total" | "deliveryDistance" | "deliveryInfo" | "specialInstructions" | "timezone" | "localDate" | "localDateTime" | "createdAt" | "updatedAt", ExtArgs["result"]["order"]>
export type OrderInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}

export type $OrderPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Order"
  objects: {
    restaurant: Prisma.$RestaurantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    restaurantId: string
    orderNumber: string
    customerId: string | null
    customerName: string
    customerEmail: string
    customerPhone: string
    customerAddress: runtime.JsonValue | null
    restaurantInfo: runtime.JsonValue
    orderType: string
    status: string
    priority: number
    paymentStatus: string
    paymentMethod: string
    paymentIntentId: string | null
    paymentClientSecret: string | null
    chargeId: string | null
    subtotal: number
    tax: number
    taxBreakdown: runtime.JsonValue | null
    tip: number
    deliveryFee: number
    platformFee: number
    total: number
    deliveryDistance: number | null
    deliveryInfo: runtime.JsonValue | null
    specialInstructions: string | null
    timezone: string
    localDate: string | null
    localDateTime: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["order"]>
  composites: {
    items: Prisma.$OrderItemPayload[]
  }
}

export type OrderGetPayload<S extends boolean | null | undefined | OrderDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$OrderPayload, S>

export type OrderCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<OrderFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: OrderCountAggregateInputType | true
  }

export interface OrderDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Order'], meta: { name: 'Order' } }
  /**
   * Find zero or one Order that matches the filter.
   * @param {OrderFindUniqueArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends OrderFindUniqueArgs>(args: Prisma.SelectSubset<T, OrderFindUniqueArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Order that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {OrderFindUniqueOrThrowArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends OrderFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, OrderFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Order that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindFirstArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends OrderFindFirstArgs>(args?: Prisma.SelectSubset<T, OrderFindFirstArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Order that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindFirstOrThrowArgs} args - Arguments to find a Order
   * @example
   * // Get one Order
   * const order = await prisma.order.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends OrderFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, OrderFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Orders
   * const orders = await prisma.order.findMany()
   * 
   * // Get first 10 Orders
   * const orders = await prisma.order.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const orderWithIdOnly = await prisma.order.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends OrderFindManyArgs>(args?: Prisma.SelectSubset<T, OrderFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Order.
   * @param {OrderCreateArgs} args - Arguments to create a Order.
   * @example
   * // Create one Order
   * const Order = await prisma.order.create({
   *   data: {
   *     // ... data to create a Order
   *   }
   * })
   * 
   */
  create<T extends OrderCreateArgs>(args: Prisma.SelectSubset<T, OrderCreateArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Orders.
   * @param {OrderCreateManyArgs} args - Arguments to create many Orders.
   * @example
   * // Create many Orders
   * const order = await prisma.order.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends OrderCreateManyArgs>(args?: Prisma.SelectSubset<T, OrderCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a Order.
   * @param {OrderDeleteArgs} args - Arguments to delete one Order.
   * @example
   * // Delete one Order
   * const Order = await prisma.order.delete({
   *   where: {
   *     // ... filter to delete one Order
   *   }
   * })
   * 
   */
  delete<T extends OrderDeleteArgs>(args: Prisma.SelectSubset<T, OrderDeleteArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Order.
   * @param {OrderUpdateArgs} args - Arguments to update one Order.
   * @example
   * // Update one Order
   * const order = await prisma.order.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends OrderUpdateArgs>(args: Prisma.SelectSubset<T, OrderUpdateArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Orders.
   * @param {OrderDeleteManyArgs} args - Arguments to filter Orders to delete.
   * @example
   * // Delete a few Orders
   * const { count } = await prisma.order.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends OrderDeleteManyArgs>(args?: Prisma.SelectSubset<T, OrderDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Orders
   * const order = await prisma.order.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends OrderUpdateManyArgs>(args: Prisma.SelectSubset<T, OrderUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one Order.
   * @param {OrderUpsertArgs} args - Arguments to update or create a Order.
   * @example
   * // Update or create a Order
   * const order = await prisma.order.upsert({
   *   create: {
   *     // ... data to create a Order
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Order we want to update
   *   }
   * })
   */
  upsert<T extends OrderUpsertArgs>(args: Prisma.SelectSubset<T, OrderUpsertArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Orders that matches the filter.
   * @param {OrderFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const order = await prisma.order.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.OrderFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a Order.
   * @param {OrderAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const order = await prisma.order.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.OrderAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of Orders.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderCountArgs} args - Arguments to filter Orders to count.
   * @example
   * // Count the number of Orders
   * const count = await prisma.order.count({
   *   where: {
   *     // ... the filter for the Orders we want to count
   *   }
   * })
  **/
  count<T extends OrderCountArgs>(
    args?: Prisma.Subset<T, OrderCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], OrderCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Order.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends OrderAggregateArgs>(args: Prisma.Subset<T, OrderAggregateArgs>): Prisma.PrismaPromise<GetOrderAggregateType<T>>

  /**
   * Group by Order.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {OrderGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends OrderGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: OrderGroupByArgs['orderBy'] }
      : { orderBy?: OrderGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, OrderGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetOrderGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Order model
 */
readonly fields: OrderFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Order.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__OrderClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>): Prisma.Prisma__RestaurantClient<runtime.Types.Result.GetResult<Prisma.$RestaurantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Order model
 */
export interface OrderFieldRefs {
  readonly id: Prisma.FieldRef<"Order", 'String'>
  readonly restaurantId: Prisma.FieldRef<"Order", 'String'>
  readonly orderNumber: Prisma.FieldRef<"Order", 'String'>
  readonly customerId: Prisma.FieldRef<"Order", 'String'>
  readonly customerName: Prisma.FieldRef<"Order", 'String'>
  readonly customerEmail: Prisma.FieldRef<"Order", 'String'>
  readonly customerPhone: Prisma.FieldRef<"Order", 'String'>
  readonly customerAddress: Prisma.FieldRef<"Order", 'Json'>
  readonly restaurantInfo: Prisma.FieldRef<"Order", 'Json'>
  readonly orderType: Prisma.FieldRef<"Order", 'String'>
  readonly status: Prisma.FieldRef<"Order", 'String'>
  readonly priority: Prisma.FieldRef<"Order", 'Int'>
  readonly paymentStatus: Prisma.FieldRef<"Order", 'String'>
  readonly paymentMethod: Prisma.FieldRef<"Order", 'String'>
  readonly paymentIntentId: Prisma.FieldRef<"Order", 'String'>
  readonly paymentClientSecret: Prisma.FieldRef<"Order", 'String'>
  readonly chargeId: Prisma.FieldRef<"Order", 'String'>
  readonly subtotal: Prisma.FieldRef<"Order", 'Float'>
  readonly tax: Prisma.FieldRef<"Order", 'Float'>
  readonly taxBreakdown: Prisma.FieldRef<"Order", 'Json'>
  readonly tip: Prisma.FieldRef<"Order", 'Float'>
  readonly deliveryFee: Prisma.FieldRef<"Order", 'Float'>
  readonly platformFee: Prisma.FieldRef<"Order", 'Float'>
  readonly total: Prisma.FieldRef<"Order", 'Float'>
  readonly deliveryDistance: Prisma.FieldRef<"Order", 'Float'>
  readonly deliveryInfo: Prisma.FieldRef<"Order", 'Json'>
  readonly specialInstructions: Prisma.FieldRef<"Order", 'String'>
  readonly timezone: Prisma.FieldRef<"Order", 'String'>
  readonly localDate: Prisma.FieldRef<"Order", 'String'>
  readonly localDateTime: Prisma.FieldRef<"Order", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Order", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Order", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Order findUnique
 */
export type OrderFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order findUniqueOrThrow
 */
export type OrderFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order findFirst
 */
export type OrderFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Orders.
   */
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order findFirstOrThrow
 */
export type OrderFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Order to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Orders.
   */
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order findMany
 */
export type OrderFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter, which Orders to fetch.
   */
  where?: Prisma.OrderWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Orders to fetch.
   */
  orderBy?: Prisma.OrderOrderByWithRelationInput | Prisma.OrderOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Orders.
   */
  cursor?: Prisma.OrderWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Orders from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Orders.
   */
  skip?: number
  distinct?: Prisma.OrderScalarFieldEnum | Prisma.OrderScalarFieldEnum[]
}

/**
 * Order create
 */
export type OrderCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The data needed to create a Order.
   */
  data: Prisma.XOR<Prisma.OrderCreateInput, Prisma.OrderUncheckedCreateInput>
}

/**
 * Order createMany
 */
export type OrderCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Orders.
   */
  data: Prisma.OrderCreateManyInput | Prisma.OrderCreateManyInput[]
}

/**
 * Order update
 */
export type OrderUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The data needed to update a Order.
   */
  data: Prisma.XOR<Prisma.OrderUpdateInput, Prisma.OrderUncheckedUpdateInput>
  /**
   * Choose, which Order to update.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order updateMany
 */
export type OrderUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Orders.
   */
  data: Prisma.XOR<Prisma.OrderUpdateManyMutationInput, Prisma.OrderUncheckedUpdateManyInput>
  /**
   * Filter which Orders to update
   */
  where?: Prisma.OrderWhereInput
  /**
   * Limit how many Orders to update.
   */
  limit?: number
}

/**
 * Order upsert
 */
export type OrderUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * The filter to search for the Order to update in case it exists.
   */
  where: Prisma.OrderWhereUniqueInput
  /**
   * In case the Order found by the `where` argument doesn't exist, create a new Order with this data.
   */
  create: Prisma.XOR<Prisma.OrderCreateInput, Prisma.OrderUncheckedCreateInput>
  /**
   * In case the Order was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.OrderUpdateInput, Prisma.OrderUncheckedUpdateInput>
}

/**
 * Order delete
 */
export type OrderDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
  /**
   * Filter which Order to delete.
   */
  where: Prisma.OrderWhereUniqueInput
}

/**
 * Order deleteMany
 */
export type OrderDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Orders to delete
   */
  where?: Prisma.OrderWhereInput
  /**
   * Limit how many Orders to delete.
   */
  limit?: number
}

/**
 * Order findRaw
 */
export type OrderFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Order aggregateRaw
 */
export type OrderAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * Order without action
 */
export type OrderDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Order
   */
  select?: Prisma.OrderSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Order
   */
  omit?: Prisma.OrderOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.OrderInclude<ExtArgs> | null
}
