
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `PriceAdjustment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PriceAdjustment
 * 
 */
export type PriceAdjustmentModel = runtime.Types.Result.DefaultSelection<Prisma.$PriceAdjustmentPayload>






export type PriceAdjustmentCompositeListFilter = {
  equals?: Prisma.PriceAdjustmentObjectEqualityInput[]
  every?: Prisma.PriceAdjustmentWhereInput
  some?: Prisma.PriceAdjustmentWhereInput
  none?: Prisma.PriceAdjustmentWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type PriceAdjustmentWhereInput = {
  AND?: Prisma.PriceAdjustmentWhereInput | Prisma.PriceAdjustmentWhereInput[]
  OR?: Prisma.PriceAdjustmentWhereInput[]
  NOT?: Prisma.PriceAdjustmentWhereInput | Prisma.PriceAdjustmentWhereInput[]
  targetOptionId?: Prisma.StringFilter<"PriceAdjustment"> | string
  targetChoiceId?: Prisma.StringNullableFilter<"PriceAdjustment"> | string | null
  adjustmentType?: Prisma.StringFilter<"PriceAdjustment"> | string
  value?: Prisma.FloatFilter<"PriceAdjustment"> | number
}

export type PriceAdjustmentListUpdateEnvelopeInput = {
  set?: Prisma.PriceAdjustmentCreateInput | Prisma.PriceAdjustmentCreateInput[]
  push?: Prisma.PriceAdjustmentCreateInput | Prisma.PriceAdjustmentCreateInput[]
  updateMany?: Prisma.PriceAdjustmentUpdateManyInput
  deleteMany?: Prisma.PriceAdjustmentDeleteManyInput
}

export type PriceAdjustmentUpdateManyInput = {
  where: Prisma.PriceAdjustmentWhereInput
  data: Prisma.PriceAdjustmentUpdateInput
}

export type PriceAdjustmentDeleteManyInput = {
  where: Prisma.PriceAdjustmentWhereInput
}

export type PriceAdjustmentUpdateInput = {
  targetOptionId?: Prisma.StringFieldUpdateOperationsInput | string
  targetChoiceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  adjustmentType?: Prisma.StringFieldUpdateOperationsInput | string
  value?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type PriceAdjustmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  targetOptionId?: boolean
  targetChoiceId?: boolean
  adjustmentType?: boolean
  value?: boolean
}, ExtArgs["result"]["priceAdjustment"]>



export type PriceAdjustmentSelectScalar = {
  targetOptionId?: boolean
  targetChoiceId?: boolean
  adjustmentType?: boolean
  value?: boolean
}

export type PriceAdjustmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"targetOptionId" | "targetChoiceId" | "adjustmentType" | "value", ExtArgs["result"]["priceAdjustment"]>

export type $PriceAdjustmentPayload = {
  name: "PriceAdjustment"
  objects: {}
  scalars: {
    targetOptionId: string
    targetChoiceId: string | null
    adjustmentType: string
    value: number
  }
  composites: {}
}

export type PriceAdjustmentGetPayload<S extends boolean | null | undefined | PriceAdjustmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PriceAdjustmentPayload, S>





/**
 * Fields of the PriceAdjustment model
 */
export interface PriceAdjustmentFieldRefs {
  readonly targetOptionId: Prisma.FieldRef<"PriceAdjustment", 'String'>
  readonly targetChoiceId: Prisma.FieldRef<"PriceAdjustment", 'String'>
  readonly adjustmentType: Prisma.FieldRef<"PriceAdjustment", 'String'>
  readonly value: Prisma.FieldRef<"PriceAdjustment", 'Float'>
}
    

// Custom InputTypes
/**
 * PriceAdjustment without action
 */
export type PriceAdjustmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PriceAdjustment
   */
  select?: Prisma.PriceAdjustmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PriceAdjustment
   */
  omit?: Prisma.PriceAdjustmentOmit<ExtArgs> | null
}
