
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `RolePermissions` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model RolePermissions
 * 
 */
export type RolePermissionsModel = runtime.Types.Result.DefaultSelection<Prisma.$RolePermissionsPayload>

export type AggregateRolePermissions = {
  _count: RolePermissionsCountAggregateOutputType | null
  _min: RolePermissionsMinAggregateOutputType | null
  _max: RolePermissionsMaxAggregateOutputType | null
}

export type RolePermissionsMinAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  role: string | null
  dashboard: boolean | null
  menuManagement: boolean | null
  orders: boolean | null
  kitchen: boolean | null
  customers: boolean | null
  marketing: boolean | null
  analytics: boolean | null
  settings: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RolePermissionsMaxAggregateOutputType = {
  id: string | null
  restaurantId: string | null
  role: string | null
  dashboard: boolean | null
  menuManagement: boolean | null
  orders: boolean | null
  kitchen: boolean | null
  customers: boolean | null
  marketing: boolean | null
  analytics: boolean | null
  settings: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type RolePermissionsCountAggregateOutputType = {
  id: number
  restaurantId: number
  role: number
  dashboard: number
  menuManagement: number
  orders: number
  kitchen: number
  customers: number
  marketing: number
  analytics: number
  settings: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type RolePermissionsMinAggregateInputType = {
  id?: true
  restaurantId?: true
  role?: true
  dashboard?: true
  menuManagement?: true
  orders?: true
  kitchen?: true
  customers?: true
  marketing?: true
  analytics?: true
  settings?: true
  createdAt?: true
  updatedAt?: true
}

export type RolePermissionsMaxAggregateInputType = {
  id?: true
  restaurantId?: true
  role?: true
  dashboard?: true
  menuManagement?: true
  orders?: true
  kitchen?: true
  customers?: true
  marketing?: true
  analytics?: true
  settings?: true
  createdAt?: true
  updatedAt?: true
}

export type RolePermissionsCountAggregateInputType = {
  id?: true
  restaurantId?: true
  role?: true
  dashboard?: true
  menuManagement?: true
  orders?: true
  kitchen?: true
  customers?: true
  marketing?: true
  analytics?: true
  settings?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type RolePermissionsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RolePermissions to aggregate.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned RolePermissions
  **/
  _count?: true | RolePermissionsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: RolePermissionsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: RolePermissionsMaxAggregateInputType
}

export type GetRolePermissionsAggregateType<T extends RolePermissionsAggregateArgs> = {
      [P in keyof T & keyof AggregateRolePermissions]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateRolePermissions[P]>
    : Prisma.GetScalarType<T[P], AggregateRolePermissions[P]>
}




export type RolePermissionsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.RolePermissionsWhereInput
  orderBy?: Prisma.RolePermissionsOrderByWithAggregationInput | Prisma.RolePermissionsOrderByWithAggregationInput[]
  by: Prisma.RolePermissionsScalarFieldEnum[] | Prisma.RolePermissionsScalarFieldEnum
  having?: Prisma.RolePermissionsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: RolePermissionsCountAggregateInputType | true
  _min?: RolePermissionsMinAggregateInputType
  _max?: RolePermissionsMaxAggregateInputType
}

export type RolePermissionsGroupByOutputType = {
  id: string
  restaurantId: string
  role: string
  dashboard: boolean
  menuManagement: boolean
  orders: boolean
  kitchen: boolean
  customers: boolean
  marketing: boolean
  analytics: boolean
  settings: boolean
  createdAt: Date
  updatedAt: Date
  _count: RolePermissionsCountAggregateOutputType | null
  _min: RolePermissionsMinAggregateOutputType | null
  _max: RolePermissionsMaxAggregateOutputType | null
}

type GetRolePermissionsGroupByPayload<T extends RolePermissionsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<RolePermissionsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof RolePermissionsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], RolePermissionsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], RolePermissionsGroupByOutputType[P]>
      }
    >
  >



export type RolePermissionsWhereInput = {
  AND?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  OR?: Prisma.RolePermissionsWhereInput[]
  NOT?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  id?: Prisma.StringFilter<"RolePermissions"> | string
  restaurantId?: Prisma.StringFilter<"RolePermissions"> | string
  role?: Prisma.StringFilter<"RolePermissions"> | string
  dashboard?: Prisma.BoolFilter<"RolePermissions"> | boolean
  menuManagement?: Prisma.BoolFilter<"RolePermissions"> | boolean
  orders?: Prisma.BoolFilter<"RolePermissions"> | boolean
  kitchen?: Prisma.BoolFilter<"RolePermissions"> | boolean
  customers?: Prisma.BoolFilter<"RolePermissions"> | boolean
  marketing?: Prisma.BoolFilter<"RolePermissions"> | boolean
  analytics?: Prisma.BoolFilter<"RolePermissions"> | boolean
  settings?: Prisma.BoolFilter<"RolePermissions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}

export type RolePermissionsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  dashboard?: Prisma.SortOrder
  menuManagement?: Prisma.SortOrder
  orders?: Prisma.SortOrder
  kitchen?: Prisma.SortOrder
  customers?: Prisma.SortOrder
  marketing?: Prisma.SortOrder
  analytics?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  restaurant?: Prisma.RestaurantOrderByWithRelationInput
}

export type RolePermissionsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  restaurantId_role?: Prisma.RolePermissionsRestaurantIdRoleCompoundUniqueInput
  AND?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  OR?: Prisma.RolePermissionsWhereInput[]
  NOT?: Prisma.RolePermissionsWhereInput | Prisma.RolePermissionsWhereInput[]
  restaurantId?: Prisma.StringFilter<"RolePermissions"> | string
  role?: Prisma.StringFilter<"RolePermissions"> | string
  dashboard?: Prisma.BoolFilter<"RolePermissions"> | boolean
  menuManagement?: Prisma.BoolFilter<"RolePermissions"> | boolean
  orders?: Prisma.BoolFilter<"RolePermissions"> | boolean
  kitchen?: Prisma.BoolFilter<"RolePermissions"> | boolean
  customers?: Prisma.BoolFilter<"RolePermissions"> | boolean
  marketing?: Prisma.BoolFilter<"RolePermissions"> | boolean
  analytics?: Prisma.BoolFilter<"RolePermissions"> | boolean
  settings?: Prisma.BoolFilter<"RolePermissions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  restaurant?: Prisma.XOR<Prisma.RestaurantScalarRelationFilter, Prisma.RestaurantWhereInput>
}, "id" | "restaurantId_role">

export type RolePermissionsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  dashboard?: Prisma.SortOrder
  menuManagement?: Prisma.SortOrder
  orders?: Prisma.SortOrder
  kitchen?: Prisma.SortOrder
  customers?: Prisma.SortOrder
  marketing?: Prisma.SortOrder
  analytics?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.RolePermissionsCountOrderByAggregateInput
  _max?: Prisma.RolePermissionsMaxOrderByAggregateInput
  _min?: Prisma.RolePermissionsMinOrderByAggregateInput
}

export type RolePermissionsScalarWhereWithAggregatesInput = {
  AND?: Prisma.RolePermissionsScalarWhereWithAggregatesInput | Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  OR?: Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.RolePermissionsScalarWhereWithAggregatesInput | Prisma.RolePermissionsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  restaurantId?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  role?: Prisma.StringWithAggregatesFilter<"RolePermissions"> | string
  dashboard?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  menuManagement?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  orders?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  kitchen?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  customers?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  marketing?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  analytics?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  settings?: Prisma.BoolWithAggregatesFilter<"RolePermissions"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"RolePermissions"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"RolePermissions"> | Date | string
}

export type RolePermissionsCreateInput = {
  id?: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
  restaurant: Prisma.RestaurantCreateNestedOneWithoutRolePermissionsInput
}

export type RolePermissionsUncheckedCreateInput = {
  id?: string
  restaurantId: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RolePermissionsUpdateInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  restaurant?: Prisma.RestaurantUpdateOneRequiredWithoutRolePermissionsNestedInput
}

export type RolePermissionsUncheckedUpdateInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsCreateManyInput = {
  id?: string
  restaurantId: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RolePermissionsUpdateManyMutationInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsUncheckedUpdateManyInput = {
  restaurantId?: Prisma.StringFieldUpdateOperationsInput | string
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsListRelationFilter = {
  every?: Prisma.RolePermissionsWhereInput
  some?: Prisma.RolePermissionsWhereInput
  none?: Prisma.RolePermissionsWhereInput
}

export type RolePermissionsOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type RolePermissionsRestaurantIdRoleCompoundUniqueInput = {
  restaurantId: string
  role: string
}

export type RolePermissionsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  dashboard?: Prisma.SortOrder
  menuManagement?: Prisma.SortOrder
  orders?: Prisma.SortOrder
  kitchen?: Prisma.SortOrder
  customers?: Prisma.SortOrder
  marketing?: Prisma.SortOrder
  analytics?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RolePermissionsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  dashboard?: Prisma.SortOrder
  menuManagement?: Prisma.SortOrder
  orders?: Prisma.SortOrder
  kitchen?: Prisma.SortOrder
  customers?: Prisma.SortOrder
  marketing?: Prisma.SortOrder
  analytics?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RolePermissionsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  restaurantId?: Prisma.SortOrder
  role?: Prisma.SortOrder
  dashboard?: Prisma.SortOrder
  menuManagement?: Prisma.SortOrder
  orders?: Prisma.SortOrder
  kitchen?: Prisma.SortOrder
  customers?: Prisma.SortOrder
  marketing?: Prisma.SortOrder
  analytics?: Prisma.SortOrder
  settings?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type RolePermissionsCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput> | Prisma.RolePermissionsCreateWithoutRestaurantInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput | Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.RolePermissionsCreateManyRestaurantInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUncheckedCreateNestedManyWithoutRestaurantInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput> | Prisma.RolePermissionsCreateWithoutRestaurantInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput | Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput[]
  createMany?: Prisma.RolePermissionsCreateManyRestaurantInputEnvelope
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
}

export type RolePermissionsUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput> | Prisma.RolePermissionsCreateWithoutRestaurantInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput | Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.RolePermissionsCreateManyRestaurantInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutRestaurantInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsUncheckedUpdateManyWithoutRestaurantNestedInput = {
  create?: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput> | Prisma.RolePermissionsCreateWithoutRestaurantInput[] | Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput[]
  connectOrCreate?: Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput | Prisma.RolePermissionsCreateOrConnectWithoutRestaurantInput[]
  upsert?: Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRestaurantInput | Prisma.RolePermissionsUpsertWithWhereUniqueWithoutRestaurantInput[]
  createMany?: Prisma.RolePermissionsCreateManyRestaurantInputEnvelope
  set?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  disconnect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  delete?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  connect?: Prisma.RolePermissionsWhereUniqueInput | Prisma.RolePermissionsWhereUniqueInput[]
  update?: Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRestaurantInput | Prisma.RolePermissionsUpdateWithWhereUniqueWithoutRestaurantInput[]
  updateMany?: Prisma.RolePermissionsUpdateManyWithWhereWithoutRestaurantInput | Prisma.RolePermissionsUpdateManyWithWhereWithoutRestaurantInput[]
  deleteMany?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
}

export type RolePermissionsCreateWithoutRestaurantInput = {
  id?: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RolePermissionsUncheckedCreateWithoutRestaurantInput = {
  id?: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RolePermissionsCreateOrConnectWithoutRestaurantInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput>
}

export type RolePermissionsCreateManyRestaurantInputEnvelope = {
  data: Prisma.RolePermissionsCreateManyRestaurantInput | Prisma.RolePermissionsCreateManyRestaurantInput[]
}

export type RolePermissionsUpsertWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  update: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedUpdateWithoutRestaurantInput>
  create: Prisma.XOR<Prisma.RolePermissionsCreateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedCreateWithoutRestaurantInput>
}

export type RolePermissionsUpdateWithWhereUniqueWithoutRestaurantInput = {
  where: Prisma.RolePermissionsWhereUniqueInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateWithoutRestaurantInput, Prisma.RolePermissionsUncheckedUpdateWithoutRestaurantInput>
}

export type RolePermissionsUpdateManyWithWhereWithoutRestaurantInput = {
  where: Prisma.RolePermissionsScalarWhereInput
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyWithoutRestaurantInput>
}

export type RolePermissionsScalarWhereInput = {
  AND?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
  OR?: Prisma.RolePermissionsScalarWhereInput[]
  NOT?: Prisma.RolePermissionsScalarWhereInput | Prisma.RolePermissionsScalarWhereInput[]
  id?: Prisma.StringFilter<"RolePermissions"> | string
  restaurantId?: Prisma.StringFilter<"RolePermissions"> | string
  role?: Prisma.StringFilter<"RolePermissions"> | string
  dashboard?: Prisma.BoolFilter<"RolePermissions"> | boolean
  menuManagement?: Prisma.BoolFilter<"RolePermissions"> | boolean
  orders?: Prisma.BoolFilter<"RolePermissions"> | boolean
  kitchen?: Prisma.BoolFilter<"RolePermissions"> | boolean
  customers?: Prisma.BoolFilter<"RolePermissions"> | boolean
  marketing?: Prisma.BoolFilter<"RolePermissions"> | boolean
  analytics?: Prisma.BoolFilter<"RolePermissions"> | boolean
  settings?: Prisma.BoolFilter<"RolePermissions"> | boolean
  createdAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"RolePermissions"> | Date | string
}

export type RolePermissionsCreateManyRestaurantInput = {
  id?: string
  role: string
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type RolePermissionsUpdateWithoutRestaurantInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsUncheckedUpdateWithoutRestaurantInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type RolePermissionsUncheckedUpdateManyWithoutRestaurantInput = {
  role?: Prisma.StringFieldUpdateOperationsInput | string
  dashboard?: Prisma.BoolFieldUpdateOperationsInput | boolean
  menuManagement?: Prisma.BoolFieldUpdateOperationsInput | boolean
  orders?: Prisma.BoolFieldUpdateOperationsInput | boolean
  kitchen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  customers?: Prisma.BoolFieldUpdateOperationsInput | boolean
  marketing?: Prisma.BoolFieldUpdateOperationsInput | boolean
  analytics?: Prisma.BoolFieldUpdateOperationsInput | boolean
  settings?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type RolePermissionsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  restaurantId?: boolean
  role?: boolean
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}, ExtArgs["result"]["rolePermissions"]>



export type RolePermissionsSelectScalar = {
  id?: boolean
  restaurantId?: boolean
  role?: boolean
  dashboard?: boolean
  menuManagement?: boolean
  orders?: boolean
  kitchen?: boolean
  customers?: boolean
  marketing?: boolean
  analytics?: boolean
  settings?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type RolePermissionsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "restaurantId" | "role" | "dashboard" | "menuManagement" | "orders" | "kitchen" | "customers" | "marketing" | "analytics" | "settings" | "createdAt" | "updatedAt", ExtArgs["result"]["rolePermissions"]>
export type RolePermissionsInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  restaurant?: boolean | Prisma.RestaurantDefaultArgs<ExtArgs>
}

export type $RolePermissionsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "RolePermissions"
  objects: {
    restaurant: Prisma.$RestaurantPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    restaurantId: string
    role: string
    dashboard: boolean
    menuManagement: boolean
    orders: boolean
    kitchen: boolean
    customers: boolean
    marketing: boolean
    analytics: boolean
    settings: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["rolePermissions"]>
  composites: {}
}

export type RolePermissionsGetPayload<S extends boolean | null | undefined | RolePermissionsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload, S>

export type RolePermissionsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<RolePermissionsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit' | 'relationLoadStrategy'> & {
    select?: RolePermissionsCountAggregateInputType | true
  }

export interface RolePermissionsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['RolePermissions'], meta: { name: 'RolePermissions' } }
  /**
   * Find zero or one RolePermissions that matches the filter.
   * @param {RolePermissionsFindUniqueArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends RolePermissionsFindUniqueArgs>(args: Prisma.SelectSubset<T, RolePermissionsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one RolePermissions that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {RolePermissionsFindUniqueOrThrowArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends RolePermissionsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, RolePermissionsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RolePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindFirstArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends RolePermissionsFindFirstArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindFirstArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first RolePermissions that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindFirstOrThrowArgs} args - Arguments to find a RolePermissions
   * @example
   * // Get one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends RolePermissionsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RolePermissions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findMany()
   * 
   * // Get first 10 RolePermissions
   * const rolePermissions = await prisma.rolePermissions.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const rolePermissionsWithIdOnly = await prisma.rolePermissions.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends RolePermissionsFindManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a RolePermissions.
   * @param {RolePermissionsCreateArgs} args - Arguments to create a RolePermissions.
   * @example
   * // Create one RolePermissions
   * const RolePermissions = await prisma.rolePermissions.create({
   *   data: {
   *     // ... data to create a RolePermissions
   *   }
   * })
   * 
   */
  create<T extends RolePermissionsCreateArgs>(args: Prisma.SelectSubset<T, RolePermissionsCreateArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many RolePermissions.
   * @param {RolePermissionsCreateManyArgs} args - Arguments to create many RolePermissions.
   * @example
   * // Create many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends RolePermissionsCreateManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Delete a RolePermissions.
   * @param {RolePermissionsDeleteArgs} args - Arguments to delete one RolePermissions.
   * @example
   * // Delete one RolePermissions
   * const RolePermissions = await prisma.rolePermissions.delete({
   *   where: {
   *     // ... filter to delete one RolePermissions
   *   }
   * })
   * 
   */
  delete<T extends RolePermissionsDeleteArgs>(args: Prisma.SelectSubset<T, RolePermissionsDeleteArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one RolePermissions.
   * @param {RolePermissionsUpdateArgs} args - Arguments to update one RolePermissions.
   * @example
   * // Update one RolePermissions
   * const rolePermissions = await prisma.rolePermissions.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends RolePermissionsUpdateArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpdateArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more RolePermissions.
   * @param {RolePermissionsDeleteManyArgs} args - Arguments to filter RolePermissions to delete.
   * @example
   * // Delete a few RolePermissions
   * const { count } = await prisma.rolePermissions.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends RolePermissionsDeleteManyArgs>(args?: Prisma.SelectSubset<T, RolePermissionsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many RolePermissions
   * const rolePermissions = await prisma.rolePermissions.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends RolePermissionsUpdateManyArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create or update one RolePermissions.
   * @param {RolePermissionsUpsertArgs} args - Arguments to update or create a RolePermissions.
   * @example
   * // Update or create a RolePermissions
   * const rolePermissions = await prisma.rolePermissions.upsert({
   *   create: {
   *     // ... data to create a RolePermissions
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the RolePermissions we want to update
   *   }
   * })
   */
  upsert<T extends RolePermissionsUpsertArgs>(args: Prisma.SelectSubset<T, RolePermissionsUpsertArgs<ExtArgs>>): Prisma.Prisma__RolePermissionsClient<runtime.Types.Result.GetResult<Prisma.$RolePermissionsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more RolePermissions that matches the filter.
   * @param {RolePermissionsFindRawArgs} args - Select which filters you would like to apply.
   * @example
   * const rolePermissions = await prisma.rolePermissions.findRaw({
   *   filter: { age: { $gt: 25 } }
   * })
   */
  findRaw(args?: Prisma.RolePermissionsFindRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>

  /**
   * Perform aggregation operations on a RolePermissions.
   * @param {RolePermissionsAggregateRawArgs} args - Select which aggregations you would like to apply.
   * @example
   * const rolePermissions = await prisma.rolePermissions.aggregateRaw({
   *   pipeline: [
   *     { $match: { status: "registered" } },
   *     { $group: { _id: "$country", total: { $sum: 1 } } }
   *   ]
   * })
   */
  aggregateRaw(args?: Prisma.RolePermissionsAggregateRawArgs): Prisma.PrismaPromise<Prisma.JsonObject>


  /**
   * Count the number of RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsCountArgs} args - Arguments to filter RolePermissions to count.
   * @example
   * // Count the number of RolePermissions
   * const count = await prisma.rolePermissions.count({
   *   where: {
   *     // ... the filter for the RolePermissions we want to count
   *   }
   * })
  **/
  count<T extends RolePermissionsCountArgs>(
    args?: Prisma.Subset<T, RolePermissionsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], RolePermissionsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends RolePermissionsAggregateArgs>(args: Prisma.Subset<T, RolePermissionsAggregateArgs>): Prisma.PrismaPromise<GetRolePermissionsAggregateType<T>>

  /**
   * Group by RolePermissions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {RolePermissionsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends RolePermissionsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: RolePermissionsGroupByArgs['orderBy'] }
      : { orderBy?: RolePermissionsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, RolePermissionsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetRolePermissionsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the RolePermissions model
 */
readonly fields: RolePermissionsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for RolePermissions.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__RolePermissionsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  restaurant<T extends Prisma.RestaurantDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.RestaurantDefaultArgs<ExtArgs>>): Prisma.Prisma__RestaurantClient<runtime.Types.Result.GetResult<Prisma.$RestaurantPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the RolePermissions model
 */
export interface RolePermissionsFieldRefs {
  readonly id: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly restaurantId: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly role: Prisma.FieldRef<"RolePermissions", 'String'>
  readonly dashboard: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly menuManagement: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly orders: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly kitchen: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly customers: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly marketing: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly analytics: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly settings: Prisma.FieldRef<"RolePermissions", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"RolePermissions", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"RolePermissions", 'DateTime'>
}
    

// Custom InputTypes
/**
 * RolePermissions findUnique
 */
export type RolePermissionsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions findUniqueOrThrow
 */
export type RolePermissionsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions findFirst
 */
export type RolePermissionsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RolePermissions.
   */
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions findFirstOrThrow
 */
export type RolePermissionsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of RolePermissions.
   */
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions findMany
 */
export type RolePermissionsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter, which RolePermissions to fetch.
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of RolePermissions to fetch.
   */
  orderBy?: Prisma.RolePermissionsOrderByWithRelationInput | Prisma.RolePermissionsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing RolePermissions.
   */
  cursor?: Prisma.RolePermissionsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` RolePermissions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` RolePermissions.
   */
  skip?: number
  distinct?: Prisma.RolePermissionsScalarFieldEnum | Prisma.RolePermissionsScalarFieldEnum[]
}

/**
 * RolePermissions create
 */
export type RolePermissionsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The data needed to create a RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsCreateInput, Prisma.RolePermissionsUncheckedCreateInput>
}

/**
 * RolePermissions createMany
 */
export type RolePermissionsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many RolePermissions.
   */
  data: Prisma.RolePermissionsCreateManyInput | Prisma.RolePermissionsCreateManyInput[]
}

/**
 * RolePermissions update
 */
export type RolePermissionsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The data needed to update a RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsUpdateInput, Prisma.RolePermissionsUncheckedUpdateInput>
  /**
   * Choose, which RolePermissions to update.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions updateMany
 */
export type RolePermissionsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update RolePermissions.
   */
  data: Prisma.XOR<Prisma.RolePermissionsUpdateManyMutationInput, Prisma.RolePermissionsUncheckedUpdateManyInput>
  /**
   * Filter which RolePermissions to update
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * Limit how many RolePermissions to update.
   */
  limit?: number
}

/**
 * RolePermissions upsert
 */
export type RolePermissionsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * The filter to search for the RolePermissions to update in case it exists.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
  /**
   * In case the RolePermissions found by the `where` argument doesn't exist, create a new RolePermissions with this data.
   */
  create: Prisma.XOR<Prisma.RolePermissionsCreateInput, Prisma.RolePermissionsUncheckedCreateInput>
  /**
   * In case the RolePermissions was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.RolePermissionsUpdateInput, Prisma.RolePermissionsUncheckedUpdateInput>
}

/**
 * RolePermissions delete
 */
export type RolePermissionsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
  /**
   * Filter which RolePermissions to delete.
   */
  where: Prisma.RolePermissionsWhereUniqueInput
}

/**
 * RolePermissions deleteMany
 */
export type RolePermissionsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which RolePermissions to delete
   */
  where?: Prisma.RolePermissionsWhereInput
  /**
   * Limit how many RolePermissions to delete.
   */
  limit?: number
}

/**
 * RolePermissions findRaw
 */
export type RolePermissionsFindRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The query predicate filter. If unspecified, then all documents in the collection will match the predicate. ${@link https://docs.mongodb.com/manual/reference/operator/query MongoDB Docs}.
   */
  filter?: runtime.InputJsonValue
  /**
   * Additional options to pass to the `find` command ${@link https://docs.mongodb.com/manual/reference/command/find/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * RolePermissions aggregateRaw
 */
export type RolePermissionsAggregateRawArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * An array of aggregation stages to process and transform the document stream via the aggregation pipeline. ${@link https://docs.mongodb.com/manual/reference/operator/aggregation-pipeline MongoDB Docs}.
   */
  pipeline?: runtime.InputJsonValue[]
  /**
   * Additional options to pass to the `aggregate` command ${@link https://docs.mongodb.com/manual/reference/command/aggregate/#command-fields MongoDB Docs}.
   */
  options?: runtime.InputJsonValue
}

/**
 * RolePermissions without action
 */
export type RolePermissionsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the RolePermissions
   */
  select?: Prisma.RolePermissionsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the RolePermissions
   */
  omit?: Prisma.RolePermissionsOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.RolePermissionsInclude<ExtArgs> | null
}
