
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `SelectedOption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model SelectedOption
 * 
 */
export type SelectedOptionModel = runtime.Types.Result.DefaultSelection<Prisma.$SelectedOptionPayload>






export type SelectedOptionCompositeListFilter = {
  equals?: Prisma.SelectedOptionObjectEqualityInput[]
  every?: Prisma.SelectedOptionWhereInput
  some?: Prisma.SelectedOptionWhereInput
  none?: Prisma.SelectedOptionWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type SelectedOptionWhereInput = {
  AND?: Prisma.SelectedOptionWhereInput | Prisma.SelectedOptionWhereInput[]
  OR?: Prisma.SelectedOptionWhereInput[]
  NOT?: Prisma.SelectedOptionWhereInput | Prisma.SelectedOptionWhereInput[]
  name?: Prisma.StringFilter<"SelectedOption"> | string
  choice?: Prisma.StringFilter<"SelectedOption"> | string
  priceAdjustment?: Prisma.FloatFilter<"SelectedOption"> | number
}

export type SelectedOptionListUpdateEnvelopeInput = {
  set?: Prisma.SelectedOptionCreateInput | Prisma.SelectedOptionCreateInput[]
  push?: Prisma.SelectedOptionCreateInput | Prisma.SelectedOptionCreateInput[]
  updateMany?: Prisma.SelectedOptionUpdateManyInput
  deleteMany?: Prisma.SelectedOptionDeleteManyInput
}

export type SelectedOptionUpdateManyInput = {
  where: Prisma.SelectedOptionWhereInput
  data: Prisma.SelectedOptionUpdateInput
}

export type SelectedOptionDeleteManyInput = {
  where: Prisma.SelectedOptionWhereInput
}

export type SelectedOptionUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  choice?: Prisma.StringFieldUpdateOperationsInput | string
  priceAdjustment?: Prisma.FloatFieldUpdateOperationsInput | number
}



export type SelectedOptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  choice?: boolean
  priceAdjustment?: boolean
}, ExtArgs["result"]["selectedOption"]>



export type SelectedOptionSelectScalar = {
  name?: boolean
  choice?: boolean
  priceAdjustment?: boolean
}

export type SelectedOptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "choice" | "priceAdjustment", ExtArgs["result"]["selectedOption"]>

export type $SelectedOptionPayload = {
  name: "SelectedOption"
  objects: {}
  scalars: {
    name: string
    choice: string
    priceAdjustment: number
  }
  composites: {}
}

export type SelectedOptionGetPayload<S extends boolean | null | undefined | SelectedOptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$SelectedOptionPayload, S>





/**
 * Fields of the SelectedOption model
 */
export interface SelectedOptionFieldRefs {
  readonly name: Prisma.FieldRef<"SelectedOption", 'String'>
  readonly choice: Prisma.FieldRef<"SelectedOption", 'String'>
  readonly priceAdjustment: Prisma.FieldRef<"SelectedOption", 'Float'>
}
    

// Custom InputTypes
/**
 * SelectedOption without action
 */
export type SelectedOptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the SelectedOption
   */
  select?: Prisma.SelectedOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the SelectedOption
   */
  omit?: Prisma.SelectedOptionOmit<ExtArgs> | null
}
