
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `TaxSetting` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model TaxSetting
 * 
 */
export type TaxSettingModel = runtime.Types.Result.DefaultSelection<Prisma.$TaxSettingPayload>






export type TaxSettingCompositeListFilter = {
  equals?: Prisma.TaxSettingObjectEqualityInput[]
  every?: Prisma.TaxSettingWhereInput
  some?: Prisma.TaxSettingWhereInput
  none?: Prisma.TaxSettingWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type TaxSettingOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type TaxSettingListCreateEnvelopeInput = {
  set?: Prisma.TaxSettingCreateInput | Prisma.TaxSettingCreateInput[]
}

export type TaxSettingListUpdateEnvelopeInput = {
  set?: Prisma.TaxSettingCreateInput | Prisma.TaxSettingCreateInput[]
  push?: Prisma.TaxSettingCreateInput | Prisma.TaxSettingCreateInput[]
  updateMany?: Prisma.TaxSettingUpdateManyInput
  deleteMany?: Prisma.TaxSettingDeleteManyInput
}

export type TaxSettingWhereInput = {
  AND?: Prisma.TaxSettingWhereInput | Prisma.TaxSettingWhereInput[]
  OR?: Prisma.TaxSettingWhereInput[]
  NOT?: Prisma.TaxSettingWhereInput | Prisma.TaxSettingWhereInput[]
  name?: Prisma.StringFilter<"TaxSetting"> | string
  enabled?: Prisma.BoolFilter<"TaxSetting"> | boolean
  rate?: Prisma.FloatFilter<"TaxSetting"> | number
  type?: Prisma.StringFilter<"TaxSetting"> | string
  applyTo?: Prisma.StringFilter<"TaxSetting"> | string
}

export type TaxSettingUpdateManyInput = {
  where: Prisma.TaxSettingWhereInput
  data: Prisma.TaxSettingUpdateInput
}

export type TaxSettingDeleteManyInput = {
  where: Prisma.TaxSettingWhereInput
}

export type TaxSettingUpdateInput = {
  name?: Prisma.StringFieldUpdateOperationsInput | string
  enabled?: Prisma.BoolFieldUpdateOperationsInput | boolean
  rate?: Prisma.FloatFieldUpdateOperationsInput | number
  type?: Prisma.StringFieldUpdateOperationsInput | string
  applyTo?: Prisma.StringFieldUpdateOperationsInput | string
}



export type TaxSettingSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  name?: boolean
  enabled?: boolean
  rate?: boolean
  type?: boolean
  applyTo?: boolean
}, ExtArgs["result"]["taxSetting"]>



export type TaxSettingSelectScalar = {
  name?: boolean
  enabled?: boolean
  rate?: boolean
  type?: boolean
  applyTo?: boolean
}

export type TaxSettingOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"name" | "enabled" | "rate" | "type" | "applyTo", ExtArgs["result"]["taxSetting"]>

export type $TaxSettingPayload = {
  name: "TaxSetting"
  objects: {}
  scalars: {
    name: string
    enabled: boolean
    rate: number
    type: string
    applyTo: string
  }
  composites: {}
}

export type TaxSettingGetPayload<S extends boolean | null | undefined | TaxSettingDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$TaxSettingPayload, S>





/**
 * Fields of the TaxSetting model
 */
export interface TaxSettingFieldRefs {
  readonly name: Prisma.FieldRef<"TaxSetting", 'String'>
  readonly enabled: Prisma.FieldRef<"TaxSetting", 'Boolean'>
  readonly rate: Prisma.FieldRef<"TaxSetting", 'Float'>
  readonly type: Prisma.FieldRef<"TaxSetting", 'String'>
  readonly applyTo: Prisma.FieldRef<"TaxSetting", 'String'>
}
    

// Custom InputTypes
/**
 * TaxSetting without action
 */
export type TaxSettingDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the TaxSetting
   */
  select?: Prisma.TaxSettingSelect<ExtArgs> | null
  /**
   * Omit specific fields from the TaxSetting
   */
  omit?: Prisma.TaxSettingOmit<ExtArgs> | null
}
