
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `WeeklySchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WeeklySchedule
 * 
 */
export type WeeklyScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$WeeklySchedulePayload>






export type WeeklyScheduleCompositeListFilter = {
  equals?: Prisma.WeeklyScheduleObjectEqualityInput[]
  every?: Prisma.WeeklyScheduleWhereInput
  some?: Prisma.WeeklyScheduleWhereInput
  none?: Prisma.WeeklyScheduleWhereInput
  isEmpty?: boolean
  isSet?: boolean
}

export type WeeklyScheduleOrderByCompositeAggregateInput = {
  _count?: Prisma.SortOrder
}

export type WeeklyScheduleListCreateEnvelopeInput = {
  set?: Prisma.WeeklyScheduleCreateInput | Prisma.WeeklyScheduleCreateInput[]
}

export type WeeklyScheduleListUpdateEnvelopeInput = {
  set?: Prisma.WeeklyScheduleCreateInput | Prisma.WeeklyScheduleCreateInput[]
  push?: Prisma.WeeklyScheduleCreateInput | Prisma.WeeklyScheduleCreateInput[]
  updateMany?: Prisma.WeeklyScheduleUpdateManyInput
  deleteMany?: Prisma.WeeklyScheduleDeleteManyInput
}

export type WeeklyScheduleWhereInput = {
  AND?: Prisma.WeeklyScheduleWhereInput | Prisma.WeeklyScheduleWhereInput[]
  OR?: Prisma.WeeklyScheduleWhereInput[]
  NOT?: Prisma.WeeklyScheduleWhereInput | Prisma.WeeklyScheduleWhereInput[]
  day?: Prisma.StringFilter<"WeeklySchedule"> | string
  isOpen?: Prisma.BoolFilter<"WeeklySchedule"> | boolean
  timeSlots?: Prisma.ScheduleTimeSlotCompositeListFilter | Prisma.ScheduleTimeSlotObjectEqualityInput[]
}

export type ScheduleTimeSlotObjectEqualityInput = {
  openTime: string
  closeTime: string
}

export type ScheduleTimeSlotCreateInput = {
  openTime?: string
  closeTime?: string
}

export type WeeklyScheduleUpdateManyInput = {
  where: Prisma.WeeklyScheduleWhereInput
  data: Prisma.WeeklyScheduleUpdateInput
}

export type WeeklyScheduleDeleteManyInput = {
  where: Prisma.WeeklyScheduleWhereInput
}

export type WeeklyScheduleUpdateInput = {
  day?: Prisma.StringFieldUpdateOperationsInput | string
  isOpen?: Prisma.BoolFieldUpdateOperationsInput | boolean
  timeSlots?: Prisma.XOR<Prisma.ScheduleTimeSlotListUpdateEnvelopeInput, Prisma.ScheduleTimeSlotCreateInput> | Prisma.ScheduleTimeSlotCreateInput[]
}



export type WeeklyScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  day?: boolean
  isOpen?: boolean
  timeSlots?: boolean | Prisma.ScheduleTimeSlotDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weeklySchedule"]>



export type WeeklyScheduleSelectScalar = {
  day?: boolean
  isOpen?: boolean
}

export type WeeklyScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"day" | "isOpen" | "timeSlots", ExtArgs["result"]["weeklySchedule"]>
export type WeeklyScheduleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $WeeklySchedulePayload = {
  name: "WeeklySchedule"
  objects: {}
  scalars: {
    day: string
    isOpen: boolean
  }
  composites: {
    timeSlots: Prisma.$ScheduleTimeSlotPayload[]
  }
}

export type WeeklyScheduleGetPayload<S extends boolean | null | undefined | WeeklyScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WeeklySchedulePayload, S>





/**
 * Fields of the WeeklySchedule model
 */
export interface WeeklyScheduleFieldRefs {
  readonly day: Prisma.FieldRef<"WeeklySchedule", 'String'>
  readonly isOpen: Prisma.FieldRef<"WeeklySchedule", 'Boolean'>
}
    

// Custom InputTypes
/**
 * WeeklySchedule without action
 */
export type WeeklyScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeeklySchedule
   */
  select?: Prisma.WeeklyScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeeklySchedule
   */
  omit?: Prisma.WeeklyScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WeeklyScheduleInclude<ExtArgs> | null
}
