
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// @ts-nocheck 
/*
 * This file exports the `WeekdaySchedule` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model WeekdaySchedule
 * 
 */
export type WeekdayScheduleModel = runtime.Types.Result.DefaultSelection<Prisma.$WeekdaySchedulePayload>






export type WeekdayScheduleNullableCompositeFilter = {
  equals?: Prisma.WeekdayScheduleObjectEqualityInput | null
  is?: Prisma.WeekdayScheduleWhereInput | null
  isNot?: Prisma.WeekdayScheduleWhereInput | null
  isSet?: boolean
}

export type WeekdayScheduleOrderByInput = {
  monday?: Prisma.DayScheduleOrderByInput
  tuesday?: Prisma.DayScheduleOrderByInput
  wednesday?: Prisma.DayScheduleOrderByInput
  thursday?: Prisma.DayScheduleOrderByInput
  friday?: Prisma.DayScheduleOrderByInput
  saturday?: Prisma.DayScheduleOrderByInput
  sunday?: Prisma.DayScheduleOrderByInput
}

export type WeekdayScheduleNullableCreateEnvelopeInput = {
  set?: Prisma.WeekdayScheduleCreateInput | null
}

export type WeekdayScheduleNullableUpdateEnvelopeInput = {
  set?: Prisma.WeekdayScheduleCreateInput | null
  upsert?: Prisma.WeekdayScheduleUpsertInput
  unset?: boolean
}

export type WeekdayScheduleWhereInput = {
  AND?: Prisma.WeekdayScheduleWhereInput | Prisma.WeekdayScheduleWhereInput[]
  OR?: Prisma.WeekdayScheduleWhereInput[]
  NOT?: Prisma.WeekdayScheduleWhereInput | Prisma.WeekdayScheduleWhereInput[]
  monday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  tuesday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  wednesday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  thursday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  friday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  saturday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
  sunday?: Prisma.XOR<Prisma.DayScheduleCompositeFilter, Prisma.DayScheduleObjectEqualityInput>
}

export type DayScheduleObjectEqualityInput = {
  available: boolean
  start: string
  end: string
}

export type DayScheduleCreateInput = {
  available?: boolean
  start?: string
  end?: string
}

export type WeekdayScheduleUpsertInput = {
  set: Prisma.WeekdayScheduleCreateInput | null
  update: Prisma.WeekdayScheduleUpdateInput
}

export type WeekdayScheduleUpdateInput = {
  monday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  tuesday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  wednesday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  thursday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  friday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  saturday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
  sunday?: Prisma.XOR<Prisma.DayScheduleUpdateEnvelopeInput, Prisma.DayScheduleCreateInput>
}



export type WeekdayScheduleSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  monday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  tuesday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  wednesday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  thursday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  friday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  saturday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
  sunday?: boolean | Prisma.DayScheduleDefaultArgs<ExtArgs>
}, ExtArgs["result"]["weekdaySchedule"]>



export type WeekdayScheduleSelectScalar = {}

export type WeekdayScheduleOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"monday" | "tuesday" | "wednesday" | "thursday" | "friday" | "saturday" | "sunday", ExtArgs["result"]["weekdaySchedule"]>
export type WeekdayScheduleInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {}

export type $WeekdaySchedulePayload = {
  name: "WeekdaySchedule"
  objects: {}
  scalars: {}
  composites: {
    monday: Prisma.$DaySchedulePayload
    tuesday: Prisma.$DaySchedulePayload
    wednesday: Prisma.$DaySchedulePayload
    thursday: Prisma.$DaySchedulePayload
    friday: Prisma.$DaySchedulePayload
    saturday: Prisma.$DaySchedulePayload
    sunday: Prisma.$DaySchedulePayload
  }
}

export type WeekdayScheduleGetPayload<S extends boolean | null | undefined | WeekdayScheduleDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$WeekdaySchedulePayload, S>





/**
 * Fields of the WeekdaySchedule model
 */
export interface WeekdayScheduleFieldRefs {

}
    

// Custom InputTypes
/**
 * WeekdaySchedule without action
 */
export type WeekdayScheduleDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the WeekdaySchedule
   */
  select?: Prisma.WeekdayScheduleSelect<ExtArgs> | null
  /**
   * Omit specific fields from the WeekdaySchedule
   */
  omit?: Prisma.WeekdayScheduleOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.WeekdayScheduleInclude<ExtArgs> | null
}
